//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Text;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct SwitchExpressionSyntaxWrapper : ISyntaxWrapper<ExpressionSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(SwitchExpressionSyntaxWrapper));
    private readonly ExpressionSyntax wrappedInstance;

    private static readonly Func<ExpressionSyntax, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>> ArmsAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>>>(WrappedType, "Arms");
    private static readonly Func<ExpressionSyntax, SyntaxToken> CloseBraceTokenAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "CloseBraceToken");
    private static readonly Func<ExpressionSyntax, ExpressionSyntax> GoverningExpressionAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, ExpressionSyntax>>(WrappedType, "GoverningExpression");
    private static readonly Func<ExpressionSyntax, SyntaxToken> OpenBraceTokenAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "OpenBraceToken");
    private static readonly Func<ExpressionSyntax, SyntaxToken> SwitchKeywordAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "SwitchKeyword");

    private static readonly Func<ExpressionSyntax, SwitchExpressionArmSyntaxWrapper[], ExpressionSyntax> AddArmsAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, SwitchExpressionArmSyntaxWrapper[], ExpressionSyntax>>(WrappedType, "AddArms");
    private static readonly Func<ExpressionSyntax, Int32, Boolean> ContainsDirectiveAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, Int32, Boolean>>(WrappedType, "ContainsDirective");
    private static readonly Func<ExpressionSyntax, SyntaxNode, Boolean> IsIncrementallyIdenticalToAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, SyntaxNode, Boolean>>(WrappedType, "IsIncrementallyIdenticalTo");
    private static readonly Func<ExpressionSyntax, ExpressionSyntax, SyntaxToken, SyntaxToken, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>, SyntaxToken, ExpressionSyntax> UpdateAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, ExpressionSyntax, SyntaxToken, SyntaxToken, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>, SyntaxToken, ExpressionSyntax>>(WrappedType, "Update");
    private static readonly Func<ExpressionSyntax, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>, ExpressionSyntax> WithArmsAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>, ExpressionSyntax>>(WrappedType, "WithArms");
    private static readonly Func<ExpressionSyntax, SyntaxToken, ExpressionSyntax> WithCloseBraceTokenAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, SyntaxToken, ExpressionSyntax>>(WrappedType, "WithCloseBraceToken");
    private static readonly Func<ExpressionSyntax, ExpressionSyntax, ExpressionSyntax> WithGoverningExpressionAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, ExpressionSyntax, ExpressionSyntax>>(WrappedType, "WithGoverningExpression");
    private static readonly Func<ExpressionSyntax, SyntaxToken, ExpressionSyntax> WithOpenBraceTokenAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, SyntaxToken, ExpressionSyntax>>(WrappedType, "WithOpenBraceToken");
    private static readonly Func<ExpressionSyntax, SyntaxToken, ExpressionSyntax> WithSwitchKeywordAccessor = AccessorFactory.CreateMethod<Func<ExpressionSyntax, SyntaxToken, ExpressionSyntax>>(WrappedType, "WithSwitchKeyword");

    private SwitchExpressionSyntaxWrapper(ExpressionSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public ExpressionSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public ExpressionSyntax SyntaxNode => wrappedInstance;

    public ExpressionSyntax WrappedInstance => wrappedInstance;

    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public String Language => wrappedInstance.Language;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;

    public SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper> Arms => ArmsAccessor(wrappedInstance);
    public SyntaxToken CloseBraceToken => (SyntaxToken)CloseBraceTokenAccessor(wrappedInstance);
    public ExpressionSyntax GoverningExpression => GoverningExpressionAccessor(wrappedInstance);
    public SyntaxToken OpenBraceToken => (SyntaxToken)OpenBraceTokenAccessor(wrappedInstance);
    public SyntaxToken SwitchKeyword => (SyntaxToken)SwitchKeywordAccessor(wrappedInstance);

    public IEnumerable<SyntaxNode> Ancestors(Boolean ascendOutOfTrivia) => wrappedInstance.Ancestors(ascendOutOfTrivia);
    public IEnumerable<SyntaxNode> AncestorsAndSelf(Boolean ascendOutOfTrivia) => wrappedInstance.AncestorsAndSelf(ascendOutOfTrivia);
    public IEnumerable<SyntaxNode> ChildNodes() => wrappedInstance.ChildNodes();
    public ChildSyntaxList ChildNodesAndTokens() => wrappedInstance.ChildNodesAndTokens();
    public SyntaxNodeOrToken ChildThatContainsPosition(Int32 position) => wrappedInstance.ChildThatContainsPosition(position);
    public IEnumerable<SyntaxToken> ChildTokens() => wrappedInstance.ChildTokens();
    public Boolean Contains(SyntaxNode node) => wrappedInstance.Contains(node);
    public IEnumerable<SyntaxNode> DescendantNodes(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodes(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodes(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodes(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodesAndSelf(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndSelf(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodesAndSelf(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndSelf(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokens(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokens(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokens(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokens(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokensAndSelf(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokensAndSelf(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokensAndSelf(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokensAndSelf(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxToken> DescendantTokens(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTokens(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxToken> DescendantTokens(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTokens(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxTrivia> DescendantTrivia(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTrivia(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxTrivia> DescendantTrivia(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTrivia(descendIntoChildren, descendIntoTrivia);
    public SyntaxNode FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie) => wrappedInstance.FindNode(span, findInsideTrivia, getInnermostNodeForTie);
    public SyntaxToken FindToken(Int32 position, Boolean findInsideTrivia) => wrappedInstance.FindToken(position, findInsideTrivia);
    public SyntaxTrivia FindTrivia(Int32 position, Boolean findInsideTrivia) => wrappedInstance.FindTrivia(position, findInsideTrivia);
    public SyntaxTrivia FindTrivia(Int32 position, Func<SyntaxTrivia, Boolean> stepInto) => wrappedInstance.FindTrivia(position, stepInto);
    public IEnumerable<SyntaxNode> GetAnnotatedNodes(SyntaxAnnotation syntaxAnnotation) => wrappedInstance.GetAnnotatedNodes(syntaxAnnotation);
    public IEnumerable<SyntaxNode> GetAnnotatedNodes(String annotationKind) => wrappedInstance.GetAnnotatedNodes(annotationKind);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(SyntaxAnnotation annotation) => wrappedInstance.GetAnnotatedNodesAndTokens(annotation);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(String annotationKind) => wrappedInstance.GetAnnotatedNodesAndTokens(annotationKind);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(String[] annotationKinds) => wrappedInstance.GetAnnotatedNodesAndTokens(annotationKinds);
    public IEnumerable<SyntaxToken> GetAnnotatedTokens(SyntaxAnnotation syntaxAnnotation) => wrappedInstance.GetAnnotatedTokens(syntaxAnnotation);
    public IEnumerable<SyntaxToken> GetAnnotatedTokens(String annotationKind) => wrappedInstance.GetAnnotatedTokens(annotationKind);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(SyntaxAnnotation annotation) => wrappedInstance.GetAnnotatedTrivia(annotation);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(String annotationKind) => wrappedInstance.GetAnnotatedTrivia(annotationKind);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(String[] annotationKinds) => wrappedInstance.GetAnnotatedTrivia(annotationKinds);
    public IEnumerable<SyntaxAnnotation> GetAnnotations(IEnumerable<String> annotationKinds) => wrappedInstance.GetAnnotations(annotationKinds);
    public IEnumerable<SyntaxAnnotation> GetAnnotations(String annotationKind) => wrappedInstance.GetAnnotations(annotationKind);
    public IEnumerable<Diagnostic> GetDiagnostics() => wrappedInstance.GetDiagnostics();
    public DirectiveTriviaSyntax GetFirstDirective(Func<DirectiveTriviaSyntax, Boolean> predicate) => wrappedInstance.GetFirstDirective(predicate);
    public SyntaxToken GetFirstToken(Boolean includeZeroWidth, Boolean includeSkipped, Boolean includeDirectives, Boolean includeDocumentationComments) => wrappedInstance.GetFirstToken(includeZeroWidth, includeSkipped, includeDirectives, includeDocumentationComments);
    public DirectiveTriviaSyntax GetLastDirective(Func<DirectiveTriviaSyntax, Boolean> predicate) => wrappedInstance.GetLastDirective(predicate);
    public SyntaxToken GetLastToken(Boolean includeZeroWidth, Boolean includeSkipped, Boolean includeDirectives, Boolean includeDocumentationComments) => wrappedInstance.GetLastToken(includeZeroWidth, includeSkipped, includeDirectives, includeDocumentationComments);
    public SyntaxTriviaList GetLeadingTrivia() => wrappedInstance.GetLeadingTrivia();
    public Location GetLocation() => wrappedInstance.GetLocation();
    public SyntaxReference GetReference() => wrappedInstance.GetReference();
    public SourceText GetText(Encoding encoding, SourceHashAlgorithm checksumAlgorithm) => wrappedInstance.GetText(encoding, checksumAlgorithm);
    public SyntaxTriviaList GetTrailingTrivia() => wrappedInstance.GetTrailingTrivia();
    public Boolean HasAnnotation(SyntaxAnnotation annotation) => wrappedInstance.HasAnnotation(annotation);
    public Boolean HasAnnotations(IEnumerable<String> annotationKinds) => wrappedInstance.HasAnnotations(annotationKinds);
    public Boolean HasAnnotations(String annotationKind) => wrappedInstance.HasAnnotations(annotationKind);
    public Boolean IsEquivalentTo(SyntaxNode other) => wrappedInstance.IsEquivalentTo(other);
    public Boolean IsEquivalentTo(SyntaxNode node, Boolean topLevel) => wrappedInstance.IsEquivalentTo(node, topLevel);
    public Boolean IsPartOfStructuredTrivia() => wrappedInstance.IsPartOfStructuredTrivia();
    public SyntaxKind Kind() => wrappedInstance.Kind();
    public String ToFullString() => wrappedInstance.ToFullString();

    public SwitchExpressionSyntaxWrapper AddArms(SwitchExpressionArmSyntaxWrapper[] items) => SwitchExpressionSyntaxWrapper.From(AddArmsAccessor(wrappedInstance, items));
    public Boolean ContainsDirective(Int32 rawKind) => (Boolean)ContainsDirectiveAccessor(wrappedInstance, rawKind);
    public Boolean IsIncrementallyIdenticalTo(SyntaxNode other) => (Boolean)IsIncrementallyIdenticalToAccessor(wrappedInstance, other);
    public SwitchExpressionSyntaxWrapper Update(ExpressionSyntax governingExpression, SyntaxToken switchKeyword, SyntaxToken openBraceToken, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper> arms, SyntaxToken closeBraceToken) => SwitchExpressionSyntaxWrapper.From(UpdateAccessor(wrappedInstance, governingExpression, switchKeyword, openBraceToken, arms, closeBraceToken));
    public SwitchExpressionSyntaxWrapper WithArms(SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper> arms) => SwitchExpressionSyntaxWrapper.From(WithArmsAccessor(wrappedInstance, arms));
    public SwitchExpressionSyntaxWrapper WithCloseBraceToken(SyntaxToken closeBraceToken) => SwitchExpressionSyntaxWrapper.From(WithCloseBraceTokenAccessor(wrappedInstance, closeBraceToken));
    public SwitchExpressionSyntaxWrapper WithGoverningExpression(ExpressionSyntax governingExpression) => SwitchExpressionSyntaxWrapper.From(WithGoverningExpressionAccessor(wrappedInstance, governingExpression));
    public SwitchExpressionSyntaxWrapper WithOpenBraceToken(SyntaxToken openBraceToken) => SwitchExpressionSyntaxWrapper.From(WithOpenBraceTokenAccessor(wrappedInstance, openBraceToken));
    public SwitchExpressionSyntaxWrapper WithSwitchKeyword(SyntaxToken switchKeyword) => SwitchExpressionSyntaxWrapper.From(WithSwitchKeywordAccessor(wrappedInstance, switchKeyword));

    public static explicit operator SwitchExpressionSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator ExpressionSyntax(SwitchExpressionSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static SwitchExpressionSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new SwitchExpressionSyntaxWrapper((ExpressionSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}