//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct ExtensionMemberCrefSyntaxWrapper : ISyntaxWrapper<MemberCrefSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.ExtensionMemberCrefSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(ExtensionMemberCrefSyntaxWrapper));
    private readonly MemberCrefSyntax wrappedInstance;

    private ExtensionMemberCrefSyntaxWrapper(MemberCrefSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public MemberCrefSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public MemberCrefSyntax SyntaxNode => wrappedInstance;

    public MemberCrefSyntax WrappedInstance => wrappedInstance;

    private static readonly Func<MemberCrefSyntax, SyntaxToken> ExtensionKeywordAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, SyntaxToken>(WrappedType, "ExtensionKeyword");
    public SyntaxToken ExtensionKeyword => (SyntaxToken)ExtensionKeywordAccessor(wrappedInstance);
    private static readonly Func<MemberCrefSyntax, TypeArgumentListSyntax> TypeArgumentListAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, TypeArgumentListSyntax>(WrappedType, "TypeArgumentList");
    public TypeArgumentListSyntax TypeArgumentList => TypeArgumentListAccessor(wrappedInstance);
    private static readonly Func<MemberCrefSyntax, CrefParameterListSyntax> ParametersAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, CrefParameterListSyntax>(WrappedType, "Parameters");
    public CrefParameterListSyntax Parameters => ParametersAccessor(wrappedInstance);
    private static readonly Func<MemberCrefSyntax, SyntaxToken> DotTokenAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, SyntaxToken>(WrappedType, "DotToken");
    public SyntaxToken DotToken => (SyntaxToken)DotTokenAccessor(wrappedInstance);
    private static readonly Func<MemberCrefSyntax, MemberCrefSyntax> MemberAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, MemberCrefSyntax>(WrappedType, "Member");
    public MemberCrefSyntax Member => MemberAccessor(wrappedInstance);
    public String Language => wrappedInstance.Language;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;

    public static explicit operator ExtensionMemberCrefSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator MemberCrefSyntax(ExtensionMemberCrefSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static ExtensionMemberCrefSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new ExtensionMemberCrefSyntaxWrapper((MemberCrefSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}