//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct SwitchExpressionSyntaxWrapper : ISyntaxWrapper<ExpressionSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(SwitchExpressionSyntaxWrapper));
    private readonly ExpressionSyntax wrappedInstance;

    private static readonly Func<ExpressionSyntax, SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper>> ArmsAccessor = LightupHelpers.CreateSeparatedSyntaxListPropertyAccessor<ExpressionSyntax, SwitchExpressionArmSyntaxWrapper>(WrappedType, nameof(Arms));
    private static readonly Func<ExpressionSyntax, SyntaxToken> CloseBraceTokenAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "CloseBraceToken");
    private static readonly Func<ExpressionSyntax, ExpressionSyntax> GoverningExpressionAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, ExpressionSyntax>>(WrappedType, "GoverningExpression");
    private static readonly Func<ExpressionSyntax, SyntaxToken> OpenBraceTokenAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "OpenBraceToken");
    private static readonly Func<ExpressionSyntax, SyntaxToken> SwitchKeywordAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "SwitchKeyword");

    private SwitchExpressionSyntaxWrapper(ExpressionSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public ExpressionSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public ExpressionSyntax SyntaxNode => wrappedInstance;

    public ExpressionSyntax WrappedInstance => wrappedInstance;

    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public String Language => wrappedInstance.Language;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;

    public SeparatedSyntaxListWrapper<SwitchExpressionArmSyntaxWrapper> Arms => ArmsAccessor(wrappedInstance);
    public SyntaxToken CloseBraceToken => (SyntaxToken)CloseBraceTokenAccessor(wrappedInstance);
    public ExpressionSyntax GoverningExpression => GoverningExpressionAccessor(wrappedInstance);
    public SyntaxToken OpenBraceToken => (SyntaxToken)OpenBraceTokenAccessor(wrappedInstance);
    public SyntaxToken SwitchKeyword => (SyntaxToken)SwitchKeywordAccessor(wrappedInstance);

    public static explicit operator SwitchExpressionSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator ExpressionSyntax(SwitchExpressionSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static SwitchExpressionSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new SwitchExpressionSyntaxWrapper((ExpressionSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}