//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct BasicBlockWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.FlowAnalysis.BasicBlock");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, IOperation> BranchValueAccessor = AccessorFactory.CreateProperty<Func<Object, IOperation>>(WrappedType, "BranchValue");
    private static readonly Func<Object, ControlFlowConditionKind> ConditionKindAccessor = AccessorFactory.CreateProperty<Func<Object, ControlFlowConditionKind>>(WrappedType, "ConditionKind");
    private static readonly Func<Object, Object> ConditionalSuccessorAccessor = AccessorFactory.CreateProperty<Func<Object, Object>>(WrappedType, "ConditionalSuccessor");
    private static readonly Func<Object, Object> EnclosingRegionAccessor = AccessorFactory.CreateProperty<Func<Object, Object>>(WrappedType, "EnclosingRegion");
    private static readonly Func<Object, Object> FallThroughSuccessorAccessor = AccessorFactory.CreateProperty<Func<Object, Object>>(WrappedType, "FallThroughSuccessor");
    private static readonly Func<Object, bool> IsReachableAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsReachable");
    private static readonly Func<Object, BasicBlockKind> KindAccessor = AccessorFactory.CreateProperty<Func<Object, BasicBlockKind>>(WrappedType, "Kind");
    private static readonly Func<Object, ImmutableArray<IOperation>> OperationsAccessor = AccessorFactory.CreateProperty<Func<Object, ImmutableArray<IOperation>>>(WrappedType, "Operations");
    private static readonly Func<Object, int> OrdinalAccessor = AccessorFactory.CreateProperty<Func<Object, int>>(WrappedType, "Ordinal");

    private BasicBlockWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    public IOperation BranchValue => BranchValueAccessor(wrappedInstance);
    public ControlFlowConditionKind ConditionKind => (ControlFlowConditionKind)ConditionKindAccessor(wrappedInstance);
    public ControlFlowBranchWrapper ConditionalSuccessor => ControlFlowBranchWrapper.From(ConditionalSuccessorAccessor(wrappedInstance));
    public ControlFlowRegionWrapper EnclosingRegion => ControlFlowRegionWrapper.From(EnclosingRegionAccessor(wrappedInstance));
    public ControlFlowBranchWrapper FallThroughSuccessor => ControlFlowBranchWrapper.From(FallThroughSuccessorAccessor(wrappedInstance));
    public bool IsReachable => (bool)IsReachableAccessor(wrappedInstance);
    public BasicBlockKind Kind => (BasicBlockKind)KindAccessor(wrappedInstance);
    public ImmutableArray<IOperation> Operations => (ImmutableArray<IOperation>)OperationsAccessor(wrappedInstance);
    public int Ordinal => (int)OrdinalAccessor(wrappedInstance);

    public static BasicBlockWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new BasicBlockWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.FlowAnalysis.BasicBlock'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}