//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;

namespace SonarAnalyzer.ShimLayer;

public static partial class DataFlowAnalysisShimExtensions
{
    private static readonly Type WrappedType = typeof(DataFlowAnalysis);

    private static readonly Func<DataFlowAnalysis, ImmutableArray<ISymbol>> CapturedInsideAccessor = AccessorFactory.CreateProperty<Func<DataFlowAnalysis, ImmutableArray<ISymbol>>>(WrappedType, "CapturedInside");
    private static readonly Func<DataFlowAnalysis, ImmutableArray<ISymbol>> CapturedOutsideAccessor = AccessorFactory.CreateProperty<Func<DataFlowAnalysis, ImmutableArray<ISymbol>>>(WrappedType, "CapturedOutside");
    private static readonly Func<DataFlowAnalysis, ImmutableArray<ISymbol>> DefinitelyAssignedOnEntryAccessor = AccessorFactory.CreateProperty<Func<DataFlowAnalysis, ImmutableArray<ISymbol>>>(WrappedType, "DefinitelyAssignedOnEntry");
    private static readonly Func<DataFlowAnalysis, ImmutableArray<ISymbol>> DefinitelyAssignedOnExitAccessor = AccessorFactory.CreateProperty<Func<DataFlowAnalysis, ImmutableArray<ISymbol>>>(WrappedType, "DefinitelyAssignedOnExit");
    private static readonly Func<DataFlowAnalysis, ImmutableArray<IMethodSymbol>> UsedLocalFunctionsAccessor = AccessorFactory.CreateProperty<Func<DataFlowAnalysis, ImmutableArray<IMethodSymbol>>>(WrappedType, "UsedLocalFunctions");

    extension(DataFlowAnalysis wrappedInstance)
    {
        public ImmutableArray<ISymbol> CapturedInside => (ImmutableArray<ISymbol>)CapturedInsideAccessor(wrappedInstance);
        public ImmutableArray<ISymbol> CapturedOutside => (ImmutableArray<ISymbol>)CapturedOutsideAccessor(wrappedInstance);
        public ImmutableArray<ISymbol> DefinitelyAssignedOnEntry => (ImmutableArray<ISymbol>)DefinitelyAssignedOnEntryAccessor(wrappedInstance);
        public ImmutableArray<ISymbol> DefinitelyAssignedOnExit => (ImmutableArray<ISymbol>)DefinitelyAssignedOnExitAccessor(wrappedInstance);
        public ImmutableArray<IMethodSymbol> UsedLocalFunctions => (ImmutableArray<IMethodSymbol>)UsedLocalFunctionsAccessor(wrappedInstance);
    }
}