//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct ISourceGeneratorWrapper : IWrapper, IEquatable<ISourceGeneratorWrapper>
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.ISourceGenerator");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Action<Object, GeneratorExecutionContextWrapper> ExecuteAccessor = AccessorFactory.CreateMethod<Action<Object, GeneratorExecutionContextWrapper>>(WrappedType, "Execute");
    private static readonly Action<Object, GeneratorInitializationContextWrapper> InitializeAccessor = AccessorFactory.CreateMethod<Action<Object, GeneratorInitializationContextWrapper>>(WrappedType, "Initialize");

    private ISourceGeneratorWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    object IWrapper.WrappedInstance => wrappedInstance;

    public override int GetHashCode() =>
        wrappedInstance?.GetHashCode() ?? 0;

    public override bool Equals(object obj) =>
        (obj is IWrapper wrapper && Equals(wrappedInstance, wrapper.WrappedInstance))
        || Equals(wrappedInstance, obj);

    public bool Equals(ISourceGeneratorWrapper other) =>
        Equals(wrappedInstance, other.wrappedInstance);

    public static bool operator ==(ISourceGeneratorWrapper left, ISourceGeneratorWrapper right) =>
        Equals(left.wrappedInstance, right.wrappedInstance);

    public static bool operator !=(ISourceGeneratorWrapper left, ISourceGeneratorWrapper right) =>
        !Equals(left.wrappedInstance, right.wrappedInstance);

    [System.ObsoleteAttribute("ISourceGenerator is deprecated and should not be implemented. Please implement IIncrementalGenerator instead. See https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md.")]
    public void Execute(GeneratorExecutionContextWrapper context) => ExecuteAccessor(wrappedInstance, context);
    [System.ObsoleteAttribute("ISourceGenerator is deprecated and should not be implemented. Please implement IIncrementalGenerator instead. See https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md.")]
    public void Initialize(GeneratorInitializationContextWrapper context) => InitializeAccessor(wrappedInstance, context);

    public static ISourceGeneratorWrapper From(object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new ISourceGeneratorWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.ISourceGenerator'");
        }
    }

    public static bool IsInstance(object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}