//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct SuppressionWrapper : IWrapper, IEquatable<SuppressionWrapper>
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.Diagnostics.Suppression");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, SuppressionDescriptorWrapper> DescriptorAccessor = AccessorFactory.CreateProperty<Func<Object, SuppressionDescriptorWrapper>>(WrappedType, "Descriptor");
    private static readonly Func<Object, Diagnostic> SuppressedDiagnosticAccessor = AccessorFactory.CreateProperty<Func<Object, Diagnostic>>(WrappedType, "SuppressedDiagnostic");

    private static readonly Func<SuppressionDescriptorWrapper, Diagnostic, SuppressionWrapper> CreateAccessor = AccessorFactory.CreateStaticMethod<Func<SuppressionDescriptorWrapper, Diagnostic, SuppressionWrapper>>(WrappedType, "Create");

    private SuppressionWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    object IWrapper.WrappedInstance => wrappedInstance;

    public override int GetHashCode() =>
        wrappedInstance?.GetHashCode() ?? 0;

    public override bool Equals(object obj) =>
        (obj is IWrapper wrapper && Equals(wrappedInstance, wrapper.WrappedInstance))
        || Equals(wrappedInstance, obj);

    public bool Equals(SuppressionWrapper other) =>
        Equals(wrappedInstance, other.wrappedInstance);

    public static bool operator ==(SuppressionWrapper left, SuppressionWrapper right) =>
        Equals(left.wrappedInstance, right.wrappedInstance);

    public static bool operator !=(SuppressionWrapper left, SuppressionWrapper right) =>
        !Equals(left.wrappedInstance, right.wrappedInstance);

    public SuppressionDescriptorWrapper Descriptor => DescriptorAccessor(wrappedInstance);
    public Diagnostic SuppressedDiagnostic => SuppressedDiagnosticAccessor(wrappedInstance);

    public static SuppressionWrapper Create(SuppressionDescriptorWrapper descriptor, Diagnostic suppressedDiagnostic) => CreateAccessor(descriptor, suppressedDiagnostic);

    public static SuppressionWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new SuppressionWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.Diagnostics.Suppression'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}