//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

internal readonly partial struct ICollectionExpressionOperationWrapper : IOperationWrapper
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.ICollectionExpressionOperation";
    private static readonly Type WrappedType;

    private readonly IOperation instance;

    static ICollectionExpressionOperationWrapper()
    {
        WrappedType = TypeRegister.LatestType(typeof(ICollectionExpressionOperationWrapper));
        ConstructMethodAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, IMethodSymbol>(WrappedType, "ConstructMethod");
        ElementsAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, ImmutableArray<IOperation>>(WrappedType, "Elements");
        ParentAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, IOperation>(WrappedType, "Parent");
        KindAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, OperationKind>(WrappedType, "Kind");
        SyntaxAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, SyntaxNode>(WrappedType, "Syntax");
        TypeAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, ITypeSymbol>(WrappedType, "Type");
        ConstantValueAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, Optional<Object>>(WrappedType, "ConstantValue");
        ChildrenAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, IEnumerable<IOperation>>(WrappedType, "Children");
        LanguageAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, String>(WrappedType, "Language");
        IsImplicitAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, Boolean>(WrappedType, "IsImplicit");
        SemanticModelAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, SemanticModel>(WrappedType, "SemanticModel");
    }

    private ICollectionExpressionOperationWrapper(IOperation instance) =>
        this.instance = instance;

    [Obsolete("Use WrappedInstance instead")]
    public IOperation WrappedOperation => this.instance;

    public IOperation WrappedInstance => this.instance;

    private static readonly Func<IOperation, IMethodSymbol> ConstructMethodAccessor;
    public IMethodSymbol ConstructMethod => (IMethodSymbol)ConstructMethodAccessor(this.instance);
    private static readonly Func<IOperation, ImmutableArray<IOperation>> ElementsAccessor;
    public ImmutableArray<IOperation> Elements => (ImmutableArray<IOperation>)ElementsAccessor(this.instance);
    private static readonly Func<IOperation, IOperation> ParentAccessor;
    public IOperation Parent => ParentAccessor(this.instance);
    private static readonly Func<IOperation, OperationKind> KindAccessor;
    public OperationKind Kind => (OperationKind)KindAccessor(this.instance);
    private static readonly Func<IOperation, SyntaxNode> SyntaxAccessor;
    public SyntaxNode Syntax => SyntaxAccessor(this.instance);
    private static readonly Func<IOperation, ITypeSymbol> TypeAccessor;
    public ITypeSymbol Type => (ITypeSymbol)TypeAccessor(this.instance);
    private static readonly Func<IOperation, Optional<Object>> ConstantValueAccessor;
    public Optional<Object> ConstantValue => (Optional<Object>)ConstantValueAccessor(this.instance);
    private static readonly Func<IOperation, IEnumerable<IOperation>> ChildrenAccessor;
    [System.ObsoleteAttribute("This API has performance penalties, please use ChildOperations instead.", false)]
    public IEnumerable<IOperation> Children => (IEnumerable<IOperation>)ChildrenAccessor(this.instance);
    private static readonly Func<IOperation, String> LanguageAccessor;
    public String Language => (String)LanguageAccessor(this.instance);
    private static readonly Func<IOperation, Boolean> IsImplicitAccessor;
    public Boolean IsImplicit => (Boolean)IsImplicitAccessor(this.instance);
    private static readonly Func<IOperation, SemanticModel> SemanticModelAccessor;
    public SemanticModel SemanticModel => (SemanticModel)SemanticModelAccessor(this.instance);

    [Obsolete("Use From instead")]
    public static ICollectionExpressionOperationWrapper FromOperation(IOperation operation) =>
        From(operation);

    public static ICollectionExpressionOperationWrapper From(IOperation operation)
    {
        if (operation is null)
        {
            return default;
        }
        else if (IsInstance(operation))
        {
            return new ICollectionExpressionOperationWrapper(operation);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{operation.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(IOperation operation) =>
        operation is not null && LightupHelpers.CanWrapOperation(operation, WrappedType);

}