//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct ExtensionBlockDeclarationSyntaxWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.CSharp.Syntax.ExtensionBlockDeclarationSyntax");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly TypeDeclarationSyntax wrappedInstance;

    private static readonly Func<TypeDeclarationSyntax, ParameterListSyntax> ParameterListAccessor = AccessorFactory.CreateProperty<Func<TypeDeclarationSyntax, ParameterListSyntax>>(WrappedType, "ParameterList");

    private static readonly Func<TypeDeclarationSyntax, AttributeListSyntax[], TypeDeclarationSyntax> AddAttributeListsAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, AttributeListSyntax[], TypeDeclarationSyntax>>(WrappedType, "AddAttributeLists");
    private static readonly Func<TypeDeclarationSyntax, BaseTypeSyntax[], BaseTypeDeclarationSyntax> AddBaseListTypesAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, BaseTypeSyntax[], BaseTypeDeclarationSyntax>>(WrappedType, "AddBaseListTypes");
    private static readonly Func<TypeDeclarationSyntax, TypeParameterConstraintClauseSyntax[], TypeDeclarationSyntax> AddConstraintClausesAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, TypeParameterConstraintClauseSyntax[], TypeDeclarationSyntax>>(WrappedType, "AddConstraintClauses");
    private static readonly Func<TypeDeclarationSyntax, MemberDeclarationSyntax[], TypeDeclarationSyntax> AddMembersAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, MemberDeclarationSyntax[], TypeDeclarationSyntax>>(WrappedType, "AddMembers");
    private static readonly Func<TypeDeclarationSyntax, SyntaxToken[], TypeDeclarationSyntax> AddModifiersAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxToken[], TypeDeclarationSyntax>>(WrappedType, "AddModifiers");
    private static readonly Func<TypeDeclarationSyntax, ParameterSyntax[], TypeDeclarationSyntax> AddParameterListParametersAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, ParameterSyntax[], TypeDeclarationSyntax>>(WrappedType, "AddParameterListParameters");
    private static readonly Func<TypeDeclarationSyntax, TypeParameterSyntax[], TypeDeclarationSyntax> AddTypeParameterListParametersAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, TypeParameterSyntax[], TypeDeclarationSyntax>>(WrappedType, "AddTypeParameterListParameters");
    private static readonly Func<TypeDeclarationSyntax, int, bool> ContainsDirectiveAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, int, bool>>(WrappedType, "ContainsDirective");
    private static readonly Func<TypeDeclarationSyntax, SyntaxNode, bool> IsIncrementallyIdenticalToAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxNode, bool>>(WrappedType, "IsIncrementallyIdenticalTo");
    private static readonly Func<TypeDeclarationSyntax, SyntaxList<AttributeListSyntax>, SyntaxTokenList, SyntaxToken, TypeParameterListSyntax, ParameterListSyntax, SyntaxList<TypeParameterConstraintClauseSyntax>, SyntaxToken, SyntaxList<MemberDeclarationSyntax>, SyntaxToken, SyntaxToken, TypeDeclarationSyntax> UpdateAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxList<AttributeListSyntax>, SyntaxTokenList, SyntaxToken, TypeParameterListSyntax, ParameterListSyntax, SyntaxList<TypeParameterConstraintClauseSyntax>, SyntaxToken, SyntaxList<MemberDeclarationSyntax>, SyntaxToken, SyntaxToken, TypeDeclarationSyntax>>(WrappedType, "Update");
    private static readonly Func<TypeDeclarationSyntax, SyntaxList<AttributeListSyntax>, TypeDeclarationSyntax> WithAttributeListsAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxList<AttributeListSyntax>, TypeDeclarationSyntax>>(WrappedType, "WithAttributeLists");
    private static readonly Func<TypeDeclarationSyntax, BaseListSyntax, TypeDeclarationSyntax> WithBaseListAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, BaseListSyntax, TypeDeclarationSyntax>>(WrappedType, "WithBaseList");
    private static readonly Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax> WithCloseBraceTokenAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax>>(WrappedType, "WithCloseBraceToken");
    private static readonly Func<TypeDeclarationSyntax, SyntaxList<TypeParameterConstraintClauseSyntax>, TypeDeclarationSyntax> WithConstraintClausesAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxList<TypeParameterConstraintClauseSyntax>, TypeDeclarationSyntax>>(WrappedType, "WithConstraintClauses");
    private static readonly Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax> WithIdentifierAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax>>(WrappedType, "WithIdentifier");
    private static readonly Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax> WithKeywordAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax>>(WrappedType, "WithKeyword");
    private static readonly Func<TypeDeclarationSyntax, SyntaxList<MemberDeclarationSyntax>, TypeDeclarationSyntax> WithMembersAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxList<MemberDeclarationSyntax>, TypeDeclarationSyntax>>(WrappedType, "WithMembers");
    private static readonly Func<TypeDeclarationSyntax, SyntaxTokenList, TypeDeclarationSyntax> WithModifiersAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxTokenList, TypeDeclarationSyntax>>(WrappedType, "WithModifiers");
    private static readonly Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax> WithOpenBraceTokenAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax>>(WrappedType, "WithOpenBraceToken");
    private static readonly Func<TypeDeclarationSyntax, ParameterListSyntax, TypeDeclarationSyntax> WithParameterListAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, ParameterListSyntax, TypeDeclarationSyntax>>(WrappedType, "WithParameterList");
    private static readonly Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax> WithSemicolonTokenAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, SyntaxToken, TypeDeclarationSyntax>>(WrappedType, "WithSemicolonToken");
    private static readonly Func<TypeDeclarationSyntax, TypeParameterListSyntax, TypeDeclarationSyntax> WithTypeParameterListAccessor = AccessorFactory.CreateMethod<Func<TypeDeclarationSyntax, TypeParameterListSyntax, TypeDeclarationSyntax>>(WrappedType, "WithTypeParameterList");

    private ExtensionBlockDeclarationSyntaxWrapper(TypeDeclarationSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public TypeDeclarationSyntax WrappedInstance => wrappedInstance;

    public int Arity => wrappedInstance.Arity;
    public SyntaxList<AttributeListSyntax> AttributeLists => wrappedInstance.AttributeLists;
    public BaseListSyntax BaseList => wrappedInstance.BaseList;
    public SyntaxToken CloseBraceToken => wrappedInstance.CloseBraceToken;
    public SyntaxList<TypeParameterConstraintClauseSyntax> ConstraintClauses => wrappedInstance.ConstraintClauses;
    public bool ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public bool ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public bool ContainsDirectives => wrappedInstance.ContainsDirectives;
    public bool ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public bool HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public bool HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public bool HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public SyntaxToken Identifier => wrappedInstance.Identifier;
    public bool IsMissing => wrappedInstance.IsMissing;
    public bool IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public SyntaxToken Keyword => wrappedInstance.Keyword;
    public string Language => wrappedInstance.Language;
    public SyntaxList<MemberDeclarationSyntax> Members => wrappedInstance.Members;
    public SyntaxTokenList Modifiers => wrappedInstance.Modifiers;
    public SyntaxToken OpenBraceToken => wrappedInstance.OpenBraceToken;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public int RawKind => wrappedInstance.RawKind;
    public SyntaxToken SemicolonToken => wrappedInstance.SemicolonToken;
    public TextSpan Span => wrappedInstance.Span;
    public int SpanStart => wrappedInstance.SpanStart;
    public TypeParameterListSyntax TypeParameterList => wrappedInstance.TypeParameterList;

    public ParameterListSyntax ParameterList => ParameterListAccessor(wrappedInstance);

    public void Accept(CSharpSyntaxVisitor visitor) => wrappedInstance.Accept(visitor);
    public IEnumerable<SyntaxNode> Ancestors(bool ascendOutOfTrivia) => wrappedInstance.Ancestors(ascendOutOfTrivia);
    public IEnumerable<SyntaxNode> AncestorsAndSelf(bool ascendOutOfTrivia) => wrappedInstance.AncestorsAndSelf(ascendOutOfTrivia);
    public IEnumerable<SyntaxNode> ChildNodes() => wrappedInstance.ChildNodes();
    public ChildSyntaxList ChildNodesAndTokens() => wrappedInstance.ChildNodesAndTokens();
    public SyntaxNodeOrToken ChildThatContainsPosition(int position) => wrappedInstance.ChildThatContainsPosition(position);
    public IEnumerable<SyntaxToken> ChildTokens() => wrappedInstance.ChildTokens();
    public bool Contains(SyntaxNode node) => wrappedInstance.Contains(node);
    public IEnumerable<SyntaxNode> DescendantNodes(TextSpan span, Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodes(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodes(Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodes(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodesAndSelf(TextSpan span, Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodesAndSelf(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodesAndSelf(Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodesAndSelf(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokens(TextSpan span, Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokens(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokens(Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokens(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokensAndSelf(TextSpan span, Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokensAndSelf(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokensAndSelf(Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokensAndSelf(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxToken> DescendantTokens(TextSpan span, Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantTokens(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxToken> DescendantTokens(Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantTokens(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxTrivia> DescendantTrivia(TextSpan span, Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantTrivia(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxTrivia> DescendantTrivia(Func<SyntaxNode, bool> descendIntoChildren, bool descendIntoTrivia) => wrappedInstance.DescendantTrivia(descendIntoChildren, descendIntoTrivia);
    public SyntaxNode FindNode(TextSpan span, bool findInsideTrivia, bool getInnermostNodeForTie) => wrappedInstance.FindNode(span, findInsideTrivia, getInnermostNodeForTie);
    public SyntaxToken FindToken(int position, bool findInsideTrivia) => wrappedInstance.FindToken(position, findInsideTrivia);
    public SyntaxTrivia FindTrivia(int position, bool findInsideTrivia) => wrappedInstance.FindTrivia(position, findInsideTrivia);
    public SyntaxTrivia FindTrivia(int position, Func<SyntaxTrivia, bool> stepInto) => wrappedInstance.FindTrivia(position, stepInto);
    public IEnumerable<SyntaxNode> GetAnnotatedNodes(SyntaxAnnotation syntaxAnnotation) => wrappedInstance.GetAnnotatedNodes(syntaxAnnotation);
    public IEnumerable<SyntaxNode> GetAnnotatedNodes(string annotationKind) => wrappedInstance.GetAnnotatedNodes(annotationKind);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(SyntaxAnnotation annotation) => wrappedInstance.GetAnnotatedNodesAndTokens(annotation);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(string annotationKind) => wrappedInstance.GetAnnotatedNodesAndTokens(annotationKind);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(string[] annotationKinds) => wrappedInstance.GetAnnotatedNodesAndTokens(annotationKinds);
    public IEnumerable<SyntaxToken> GetAnnotatedTokens(SyntaxAnnotation syntaxAnnotation) => wrappedInstance.GetAnnotatedTokens(syntaxAnnotation);
    public IEnumerable<SyntaxToken> GetAnnotatedTokens(string annotationKind) => wrappedInstance.GetAnnotatedTokens(annotationKind);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(SyntaxAnnotation annotation) => wrappedInstance.GetAnnotatedTrivia(annotation);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(string annotationKind) => wrappedInstance.GetAnnotatedTrivia(annotationKind);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(string[] annotationKinds) => wrappedInstance.GetAnnotatedTrivia(annotationKinds);
    public IEnumerable<SyntaxAnnotation> GetAnnotations(IEnumerable<string> annotationKinds) => wrappedInstance.GetAnnotations(annotationKinds);
    public IEnumerable<SyntaxAnnotation> GetAnnotations(string annotationKind) => wrappedInstance.GetAnnotations(annotationKind);
    public IEnumerable<Diagnostic> GetDiagnostics() => wrappedInstance.GetDiagnostics();
    public DirectiveTriviaSyntax GetFirstDirective(Func<DirectiveTriviaSyntax, bool> predicate) => wrappedInstance.GetFirstDirective(predicate);
    public SyntaxToken GetFirstToken(bool includeZeroWidth, bool includeSkipped, bool includeDirectives, bool includeDocumentationComments) => wrappedInstance.GetFirstToken(includeZeroWidth, includeSkipped, includeDirectives, includeDocumentationComments);
    public DirectiveTriviaSyntax GetLastDirective(Func<DirectiveTriviaSyntax, bool> predicate) => wrappedInstance.GetLastDirective(predicate);
    public SyntaxToken GetLastToken(bool includeZeroWidth, bool includeSkipped, bool includeDirectives, bool includeDocumentationComments) => wrappedInstance.GetLastToken(includeZeroWidth, includeSkipped, includeDirectives, includeDocumentationComments);
    public SyntaxTriviaList GetLeadingTrivia() => wrappedInstance.GetLeadingTrivia();
    public Location GetLocation() => wrappedInstance.GetLocation();
    public SyntaxReference GetReference() => wrappedInstance.GetReference();
    public SourceText GetText(Encoding encoding, SourceHashAlgorithm checksumAlgorithm) => wrappedInstance.GetText(encoding, checksumAlgorithm);
    public SyntaxTriviaList GetTrailingTrivia() => wrappedInstance.GetTrailingTrivia();
    public bool HasAnnotation(SyntaxAnnotation annotation) => wrappedInstance.HasAnnotation(annotation);
    public bool HasAnnotations(IEnumerable<string> annotationKinds) => wrappedInstance.HasAnnotations(annotationKinds);
    public bool HasAnnotations(string annotationKind) => wrappedInstance.HasAnnotations(annotationKind);
    public bool IsEquivalentTo(SyntaxNode other) => wrappedInstance.IsEquivalentTo(other);
    public bool IsEquivalentTo(SyntaxNode node, bool topLevel) => wrappedInstance.IsEquivalentTo(node, topLevel);
    public bool IsPartOfStructuredTrivia() => wrappedInstance.IsPartOfStructuredTrivia();
    public SyntaxKind Kind() => wrappedInstance.Kind();
    [System.ObsoleteAttribute("Syntax serialization support is no longer supported", true)]
    public void SerializeTo(Stream stream, CancellationToken cancellationToken) => wrappedInstance.SerializeTo(stream, cancellationToken);
    public string ToFullString() => wrappedInstance.ToFullString();
    public void WriteTo(TextWriter writer) => wrappedInstance.WriteTo(writer);

    public ExtensionBlockDeclarationSyntaxWrapper AddAttributeLists(AttributeListSyntax[] items) => ExtensionBlockDeclarationSyntaxWrapper.From(AddAttributeListsAccessor(wrappedInstance, items));
    public BaseTypeDeclarationSyntax AddBaseListTypes(BaseTypeSyntax[] items) => AddBaseListTypesAccessor(wrappedInstance, items);
    public ExtensionBlockDeclarationSyntaxWrapper AddConstraintClauses(TypeParameterConstraintClauseSyntax[] items) => ExtensionBlockDeclarationSyntaxWrapper.From(AddConstraintClausesAccessor(wrappedInstance, items));
    public ExtensionBlockDeclarationSyntaxWrapper AddMembers(MemberDeclarationSyntax[] items) => ExtensionBlockDeclarationSyntaxWrapper.From(AddMembersAccessor(wrappedInstance, items));
    public ExtensionBlockDeclarationSyntaxWrapper AddModifiers(SyntaxToken[] items) => ExtensionBlockDeclarationSyntaxWrapper.From(AddModifiersAccessor(wrappedInstance, items));
    public ExtensionBlockDeclarationSyntaxWrapper AddParameterListParameters(ParameterSyntax[] items) => ExtensionBlockDeclarationSyntaxWrapper.From(AddParameterListParametersAccessor(wrappedInstance, items));
    public ExtensionBlockDeclarationSyntaxWrapper AddTypeParameterListParameters(TypeParameterSyntax[] items) => ExtensionBlockDeclarationSyntaxWrapper.From(AddTypeParameterListParametersAccessor(wrappedInstance, items));
    public bool ContainsDirective(int rawKind) => (bool)ContainsDirectiveAccessor(wrappedInstance, rawKind);
    public bool IsIncrementallyIdenticalTo(SyntaxNode other) => (bool)IsIncrementallyIdenticalToAccessor(wrappedInstance, other);
    public ExtensionBlockDeclarationSyntaxWrapper Update(SyntaxList<AttributeListSyntax> attributeLists, SyntaxTokenList modifiers, SyntaxToken keyword, TypeParameterListSyntax typeParameterList, ParameterListSyntax parameterList, SyntaxList<TypeParameterConstraintClauseSyntax> constraintClauses, SyntaxToken openBraceToken, SyntaxList<MemberDeclarationSyntax> members, SyntaxToken closeBraceToken, SyntaxToken semicolonToken) => ExtensionBlockDeclarationSyntaxWrapper.From(UpdateAccessor(wrappedInstance, attributeLists, modifiers, keyword, typeParameterList, parameterList, constraintClauses, openBraceToken, members, closeBraceToken, semicolonToken));
    public ExtensionBlockDeclarationSyntaxWrapper WithAttributeLists(SyntaxList<AttributeListSyntax> attributeLists) => ExtensionBlockDeclarationSyntaxWrapper.From(WithAttributeListsAccessor(wrappedInstance, attributeLists));
    public TypeDeclarationSyntax WithBaseList(BaseListSyntax baseList) => WithBaseListAccessor(wrappedInstance, baseList);
    public ExtensionBlockDeclarationSyntaxWrapper WithCloseBraceToken(SyntaxToken closeBraceToken) => ExtensionBlockDeclarationSyntaxWrapper.From(WithCloseBraceTokenAccessor(wrappedInstance, closeBraceToken));
    public ExtensionBlockDeclarationSyntaxWrapper WithConstraintClauses(SyntaxList<TypeParameterConstraintClauseSyntax> constraintClauses) => ExtensionBlockDeclarationSyntaxWrapper.From(WithConstraintClausesAccessor(wrappedInstance, constraintClauses));
    public TypeDeclarationSyntax WithIdentifier(SyntaxToken identifier) => WithIdentifierAccessor(wrappedInstance, identifier);
    public ExtensionBlockDeclarationSyntaxWrapper WithKeyword(SyntaxToken keyword) => ExtensionBlockDeclarationSyntaxWrapper.From(WithKeywordAccessor(wrappedInstance, keyword));
    public ExtensionBlockDeclarationSyntaxWrapper WithMembers(SyntaxList<MemberDeclarationSyntax> members) => ExtensionBlockDeclarationSyntaxWrapper.From(WithMembersAccessor(wrappedInstance, members));
    public ExtensionBlockDeclarationSyntaxWrapper WithModifiers(SyntaxTokenList modifiers) => ExtensionBlockDeclarationSyntaxWrapper.From(WithModifiersAccessor(wrappedInstance, modifiers));
    public ExtensionBlockDeclarationSyntaxWrapper WithOpenBraceToken(SyntaxToken openBraceToken) => ExtensionBlockDeclarationSyntaxWrapper.From(WithOpenBraceTokenAccessor(wrappedInstance, openBraceToken));
    public ExtensionBlockDeclarationSyntaxWrapper WithParameterList(ParameterListSyntax parameterList) => ExtensionBlockDeclarationSyntaxWrapper.From(WithParameterListAccessor(wrappedInstance, parameterList));
    public ExtensionBlockDeclarationSyntaxWrapper WithSemicolonToken(SyntaxToken semicolonToken) => ExtensionBlockDeclarationSyntaxWrapper.From(WithSemicolonTokenAccessor(wrappedInstance, semicolonToken));
    public ExtensionBlockDeclarationSyntaxWrapper WithTypeParameterList(TypeParameterListSyntax typeParameterList) => ExtensionBlockDeclarationSyntaxWrapper.From(WithTypeParameterListAccessor(wrappedInstance, typeParameterList));

    public static explicit operator ExtensionBlockDeclarationSyntaxWrapper(SyntaxNode instance) =>
        From(instance);

    public static implicit operator TypeDeclarationSyntax(ExtensionBlockDeclarationSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static ExtensionBlockDeclarationSyntaxWrapper From(SyntaxNode instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new ExtensionBlockDeclarationSyntaxWrapper((TypeDeclarationSyntax)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.CSharp.Syntax.ExtensionBlockDeclarationSyntax'");
        }
    }

    public static bool IsInstance(SyntaxNode instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}