//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class IErrorTypeSymbolShimExtensions
{
    private static readonly Type WrappedType = typeof(IErrorTypeSymbol);

    private static readonly Func<IErrorTypeSymbol, string> ExtensionGroupingNameAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, string>>(WrappedType, "ExtensionGroupingName");
    private static readonly Func<IErrorTypeSymbol, string> ExtensionMarkerNameAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, string>>(WrappedType, "ExtensionMarkerName");
    private static readonly Func<IErrorTypeSymbol, IParameterSymbol> ExtensionParameterAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, IParameterSymbol>>(WrappedType, "ExtensionParameter");
    private static readonly Func<IErrorTypeSymbol, bool> IsComImportAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsComImport");
    private static readonly Func<IErrorTypeSymbol, bool> IsExtensionAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsExtension");
    private static readonly Func<IErrorTypeSymbol, bool> IsFileLocalAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsFileLocal");
    private static readonly Func<IErrorTypeSymbol, bool> IsNativeIntegerTypeAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsNativeIntegerType");
    private static readonly Func<IErrorTypeSymbol, bool> IsReadOnlyAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsReadOnly");
    private static readonly Func<IErrorTypeSymbol, bool> IsRecordAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsRecord");
    private static readonly Func<IErrorTypeSymbol, bool> IsRefLikeTypeAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsRefLikeType");
    private static readonly Func<IErrorTypeSymbol, bool> IsSerializableAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsSerializable");
    private static readonly Func<IErrorTypeSymbol, bool> IsTupleTypeAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsTupleType");
    private static readonly Func<IErrorTypeSymbol, bool> IsUnmanagedTypeAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, bool>>(WrappedType, "IsUnmanagedType");
    private static readonly Func<IErrorTypeSymbol, int> MetadataTokenAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, int>>(WrappedType, "MetadataToken");
    private static readonly Func<IErrorTypeSymbol, INamedTypeSymbol> NativeIntegerUnderlyingTypeAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, INamedTypeSymbol>>(WrappedType, "NativeIntegerUnderlyingType");
    private static readonly Func<IErrorTypeSymbol, NullableAnnotation> NullableAnnotationAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, NullableAnnotation>>(WrappedType, "NullableAnnotation");
    private static readonly Func<IErrorTypeSymbol, ImmutableArray<IFieldSymbol>> TupleElementsAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, ImmutableArray<IFieldSymbol>>>(WrappedType, "TupleElements");
    private static readonly Func<IErrorTypeSymbol, INamedTypeSymbol> TupleUnderlyingTypeAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, INamedTypeSymbol>>(WrappedType, "TupleUnderlyingType");
    private static readonly Func<IErrorTypeSymbol, ImmutableArray<NullableAnnotation>> TypeArgumentNullableAnnotationsAccessor = AccessorFactory.CreateProperty<Func<IErrorTypeSymbol, ImmutableArray<NullableAnnotation>>>(WrappedType, "TypeArgumentNullableAnnotations");

    private static readonly Func<IErrorTypeSymbol, ImmutableArray<ITypeSymbol>, ImmutableArray<NullableAnnotation>, INamedTypeSymbol> ConstructAccessor_Overload2 = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, ImmutableArray<ITypeSymbol>, ImmutableArray<NullableAnnotation>, INamedTypeSymbol>>(WrappedType, "Construct");
    private static readonly Func<IErrorTypeSymbol, int, ImmutableArray<CustomModifier>> GetTypeArgumentCustomModifiersAccessor = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, int, ImmutableArray<CustomModifier>>>(WrappedType, "GetTypeArgumentCustomModifiers");
    private static readonly Func<IErrorTypeSymbol, NullableFlowState, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>> ToDisplayPartsAccessor = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, NullableFlowState, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>>>(WrappedType, "ToDisplayParts");
    private static readonly Func<IErrorTypeSymbol, NullableFlowState, SymbolDisplayFormat, string> ToDisplayStringAccessor = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, NullableFlowState, SymbolDisplayFormat, string>>(WrappedType, "ToDisplayString");
    private static readonly Func<IErrorTypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>> ToMinimalDisplayPartsAccessor = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>>>(WrappedType, "ToMinimalDisplayParts");
    private static readonly Func<IErrorTypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, string> ToMinimalDisplayStringAccessor = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, string>>(WrappedType, "ToMinimalDisplayString");
    private static readonly Func<IErrorTypeSymbol, NullableAnnotation, ITypeSymbol> WithNullableAnnotationAccessor = AccessorFactory.CreateMethod<Func<IErrorTypeSymbol, NullableAnnotation, ITypeSymbol>>(WrappedType, "WithNullableAnnotation");

    extension(IErrorTypeSymbol wrappedInstance)
    {
        public string ExtensionGroupingName => ExtensionGroupingNameAccessor(wrappedInstance);
        public string ExtensionMarkerName => ExtensionMarkerNameAccessor(wrappedInstance);
        public IParameterSymbol ExtensionParameter => ExtensionParameterAccessor(wrappedInstance);
        public bool IsComImport => IsComImportAccessor(wrappedInstance);
        public bool IsExtension => IsExtensionAccessor(wrappedInstance);
        public bool IsFileLocal => IsFileLocalAccessor(wrappedInstance);
        public bool IsNativeIntegerType => IsNativeIntegerTypeAccessor(wrappedInstance);
        public bool IsReadOnly => IsReadOnlyAccessor(wrappedInstance);
        public bool IsRecord => IsRecordAccessor(wrappedInstance);
        public bool IsRefLikeType => IsRefLikeTypeAccessor(wrappedInstance);
        public bool IsSerializable => IsSerializableAccessor(wrappedInstance);
        public bool IsTupleType => IsTupleTypeAccessor(wrappedInstance);
        public bool IsUnmanagedType => IsUnmanagedTypeAccessor(wrappedInstance);
        public int MetadataToken => MetadataTokenAccessor(wrappedInstance);
        public INamedTypeSymbol NativeIntegerUnderlyingType => NativeIntegerUnderlyingTypeAccessor(wrappedInstance);
        public NullableAnnotation NullableAnnotation => NullableAnnotationAccessor(wrappedInstance);
        public ImmutableArray<IFieldSymbol> TupleElements => TupleElementsAccessor(wrappedInstance);
        public INamedTypeSymbol TupleUnderlyingType => TupleUnderlyingTypeAccessor(wrappedInstance);
        public ImmutableArray<NullableAnnotation> TypeArgumentNullableAnnotations => TypeArgumentNullableAnnotationsAccessor(wrappedInstance);

        public INamedTypeSymbol Construct(ImmutableArray<ITypeSymbol> typeArguments, ImmutableArray<NullableAnnotation> typeArgumentNullableAnnotations) => ConstructAccessor_Overload2(wrappedInstance, typeArguments, typeArgumentNullableAnnotations);
        public ImmutableArray<CustomModifier> GetTypeArgumentCustomModifiers(int ordinal) => GetTypeArgumentCustomModifiersAccessor(wrappedInstance, ordinal);
        public ImmutableArray<SymbolDisplayPart> ToDisplayParts(NullableFlowState topLevelNullability, SymbolDisplayFormat format) => ToDisplayPartsAccessor(wrappedInstance, topLevelNullability, format);
        public string ToDisplayString(NullableFlowState topLevelNullability, SymbolDisplayFormat format) => ToDisplayStringAccessor(wrappedInstance, topLevelNullability, format);
        public ImmutableArray<SymbolDisplayPart> ToMinimalDisplayParts(SemanticModel semanticModel, NullableFlowState topLevelNullability, int position, SymbolDisplayFormat format) => ToMinimalDisplayPartsAccessor(wrappedInstance, semanticModel, topLevelNullability, position, format);
        public string ToMinimalDisplayString(SemanticModel semanticModel, NullableFlowState topLevelNullability, int position, SymbolDisplayFormat format) => ToMinimalDisplayStringAccessor(wrappedInstance, semanticModel, topLevelNullability, position, format);
        public ITypeSymbol WithNullableAnnotation(NullableAnnotation nullableAnnotation) => WithNullableAnnotationAccessor(wrappedInstance, nullableAnnotation);
    }
}