//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Text;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct SingleVariableDesignationSyntaxWrapper : ISyntaxWrapper<CSharpSyntaxNode>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.SingleVariableDesignationSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(SingleVariableDesignationSyntaxWrapper));
    private readonly CSharpSyntaxNode wrappedInstance;

    private static readonly Func<CSharpSyntaxNode, SyntaxToken> IdentifierAccessor = AccessorFactory.CreateProperty<Func<CSharpSyntaxNode, SyntaxToken>>(WrappedType, "Identifier");

    private SingleVariableDesignationSyntaxWrapper(CSharpSyntaxNode wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public CSharpSyntaxNode Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public CSharpSyntaxNode SyntaxNode => wrappedInstance;

    public CSharpSyntaxNode WrappedInstance => wrappedInstance;

    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public String Language => wrappedInstance.Language;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;

    public SyntaxToken Identifier => (SyntaxToken)IdentifierAccessor(wrappedInstance);

    public IEnumerable<SyntaxNode> Ancestors(Boolean ascendOutOfTrivia) => wrappedInstance.Ancestors(ascendOutOfTrivia);
    public IEnumerable<SyntaxNode> AncestorsAndSelf(Boolean ascendOutOfTrivia) => wrappedInstance.AncestorsAndSelf(ascendOutOfTrivia);
    public IEnumerable<SyntaxNode> ChildNodes() => wrappedInstance.ChildNodes();
    public ChildSyntaxList ChildNodesAndTokens() => wrappedInstance.ChildNodesAndTokens();
    public SyntaxNodeOrToken ChildThatContainsPosition(Int32 position) => wrappedInstance.ChildThatContainsPosition(position);
    public IEnumerable<SyntaxToken> ChildTokens() => wrappedInstance.ChildTokens();
    public Boolean Contains(SyntaxNode node) => wrappedInstance.Contains(node);
    public IEnumerable<SyntaxNode> DescendantNodes(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodes(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodes(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodes(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodesAndSelf(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndSelf(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNode> DescendantNodesAndSelf(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndSelf(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokens(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokens(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokens(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokens(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokensAndSelf(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokensAndSelf(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxNodeOrToken> DescendantNodesAndTokensAndSelf(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantNodesAndTokensAndSelf(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxToken> DescendantTokens(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTokens(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxToken> DescendantTokens(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTokens(descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxTrivia> DescendantTrivia(TextSpan span, Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTrivia(span, descendIntoChildren, descendIntoTrivia);
    public IEnumerable<SyntaxTrivia> DescendantTrivia(Func<SyntaxNode, Boolean> descendIntoChildren, Boolean descendIntoTrivia) => wrappedInstance.DescendantTrivia(descendIntoChildren, descendIntoTrivia);
    public SyntaxNode FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie) => wrappedInstance.FindNode(span, findInsideTrivia, getInnermostNodeForTie);
    public SyntaxToken FindToken(Int32 position, Boolean findInsideTrivia) => wrappedInstance.FindToken(position, findInsideTrivia);
    public SyntaxTrivia FindTrivia(Int32 position, Boolean findInsideTrivia) => wrappedInstance.FindTrivia(position, findInsideTrivia);
    public SyntaxTrivia FindTrivia(Int32 position, Func<SyntaxTrivia, Boolean> stepInto) => wrappedInstance.FindTrivia(position, stepInto);
    public IEnumerable<SyntaxNode> GetAnnotatedNodes(SyntaxAnnotation syntaxAnnotation) => wrappedInstance.GetAnnotatedNodes(syntaxAnnotation);
    public IEnumerable<SyntaxNode> GetAnnotatedNodes(String annotationKind) => wrappedInstance.GetAnnotatedNodes(annotationKind);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(SyntaxAnnotation annotation) => wrappedInstance.GetAnnotatedNodesAndTokens(annotation);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(String annotationKind) => wrappedInstance.GetAnnotatedNodesAndTokens(annotationKind);
    public IEnumerable<SyntaxNodeOrToken> GetAnnotatedNodesAndTokens(String[] annotationKinds) => wrappedInstance.GetAnnotatedNodesAndTokens(annotationKinds);
    public IEnumerable<SyntaxToken> GetAnnotatedTokens(SyntaxAnnotation syntaxAnnotation) => wrappedInstance.GetAnnotatedTokens(syntaxAnnotation);
    public IEnumerable<SyntaxToken> GetAnnotatedTokens(String annotationKind) => wrappedInstance.GetAnnotatedTokens(annotationKind);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(SyntaxAnnotation annotation) => wrappedInstance.GetAnnotatedTrivia(annotation);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(String annotationKind) => wrappedInstance.GetAnnotatedTrivia(annotationKind);
    public IEnumerable<SyntaxTrivia> GetAnnotatedTrivia(String[] annotationKinds) => wrappedInstance.GetAnnotatedTrivia(annotationKinds);
    public IEnumerable<SyntaxAnnotation> GetAnnotations(IEnumerable<String> annotationKinds) => wrappedInstance.GetAnnotations(annotationKinds);
    public IEnumerable<SyntaxAnnotation> GetAnnotations(String annotationKind) => wrappedInstance.GetAnnotations(annotationKind);
    public IEnumerable<Diagnostic> GetDiagnostics() => wrappedInstance.GetDiagnostics();
    public DirectiveTriviaSyntax GetFirstDirective(Func<DirectiveTriviaSyntax, Boolean> predicate) => wrappedInstance.GetFirstDirective(predicate);
    public SyntaxToken GetFirstToken(Boolean includeZeroWidth, Boolean includeSkipped, Boolean includeDirectives, Boolean includeDocumentationComments) => wrappedInstance.GetFirstToken(includeZeroWidth, includeSkipped, includeDirectives, includeDocumentationComments);
    public DirectiveTriviaSyntax GetLastDirective(Func<DirectiveTriviaSyntax, Boolean> predicate) => wrappedInstance.GetLastDirective(predicate);
    public SyntaxToken GetLastToken(Boolean includeZeroWidth, Boolean includeSkipped, Boolean includeDirectives, Boolean includeDocumentationComments) => wrappedInstance.GetLastToken(includeZeroWidth, includeSkipped, includeDirectives, includeDocumentationComments);
    public SyntaxTriviaList GetLeadingTrivia() => wrappedInstance.GetLeadingTrivia();
    public Location GetLocation() => wrappedInstance.GetLocation();
    public SyntaxReference GetReference() => wrappedInstance.GetReference();
    public SourceText GetText(Encoding encoding, SourceHashAlgorithm checksumAlgorithm) => wrappedInstance.GetText(encoding, checksumAlgorithm);
    public SyntaxTriviaList GetTrailingTrivia() => wrappedInstance.GetTrailingTrivia();
    public Boolean HasAnnotation(SyntaxAnnotation annotation) => wrappedInstance.HasAnnotation(annotation);
    public Boolean HasAnnotations(IEnumerable<String> annotationKinds) => wrappedInstance.HasAnnotations(annotationKinds);
    public Boolean HasAnnotations(String annotationKind) => wrappedInstance.HasAnnotations(annotationKind);
    public Boolean IsEquivalentTo(SyntaxNode other) => wrappedInstance.IsEquivalentTo(other);
    public Boolean IsEquivalentTo(SyntaxNode node, Boolean topLevel) => wrappedInstance.IsEquivalentTo(node, topLevel);
    public Boolean IsPartOfStructuredTrivia() => wrappedInstance.IsPartOfStructuredTrivia();
    public SyntaxKind Kind() => wrappedInstance.Kind();
    public String ToFullString() => wrappedInstance.ToFullString();

    public static explicit operator SingleVariableDesignationSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator CSharpSyntaxNode(SingleVariableDesignationSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static SingleVariableDesignationSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new SingleVariableDesignationSyntaxWrapper((CSharpSyntaxNode)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

    public static implicit operator VariableDesignationSyntaxWrapper(SingleVariableDesignationSyntaxWrapper up) => VariableDesignationSyntaxWrapper.From(up.WrappedInstance);
    public static explicit operator SingleVariableDesignationSyntaxWrapper(VariableDesignationSyntaxWrapper down) => SingleVariableDesignationSyntaxWrapper.From(down.WrappedInstance);

}