//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct BinaryPatternSyntaxWrapper : ISyntaxWrapper<CSharpSyntaxNode>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.BinaryPatternSyntax";
    private static readonly Type WrappedType;

    private readonly CSharpSyntaxNode instance;

    static BinaryPatternSyntaxWrapper()
    {
        WrappedType = TypeRegister.LatestType(typeof(BinaryPatternSyntaxWrapper));
        LeftAccessor = LightupHelpers.CreatePropertyAccessor<CSharpSyntaxNode, CSharpSyntaxNode>(WrappedType, "Left");
        OperatorTokenAccessor = LightupHelpers.CreatePropertyAccessor<CSharpSyntaxNode, SyntaxToken>(WrappedType, "OperatorToken");
        RightAccessor = LightupHelpers.CreatePropertyAccessor<CSharpSyntaxNode, CSharpSyntaxNode>(WrappedType, "Right");
    }

    private BinaryPatternSyntaxWrapper(CSharpSyntaxNode instance) =>
        this.instance = instance;

    [Obsolete("Use WrappedInstance instead")]
    public CSharpSyntaxNode Node => this.instance;

    [Obsolete("Use WrappedInstance instead")]
    public CSharpSyntaxNode SyntaxNode => this.instance;

    public CSharpSyntaxNode WrappedInstance => this.instance;

    private static readonly Func<CSharpSyntaxNode, CSharpSyntaxNode> LeftAccessor;
    public PatternSyntaxWrapper Left => PatternSyntaxWrapper.From(LeftAccessor(this.instance));
    private static readonly Func<CSharpSyntaxNode, SyntaxToken> OperatorTokenAccessor;
    public SyntaxToken OperatorToken => (SyntaxToken)OperatorTokenAccessor(this.instance);
    private static readonly Func<CSharpSyntaxNode, CSharpSyntaxNode> RightAccessor;
    public PatternSyntaxWrapper Right => PatternSyntaxWrapper.From(RightAccessor(this.instance));
    public String Language => this.instance.Language;
    public Int32 RawKind => this.instance.RawKind;
    public TextSpan FullSpan => this.instance.FullSpan;
    public TextSpan Span => this.instance.Span;
    public Int32 SpanStart => this.instance.SpanStart;
    public Boolean IsMissing => this.instance.IsMissing;
    public Boolean IsStructuredTrivia => this.instance.IsStructuredTrivia;
    public Boolean HasStructuredTrivia => this.instance.HasStructuredTrivia;
    public Boolean ContainsSkippedText => this.instance.ContainsSkippedText;
    public Boolean ContainsDiagnostics => this.instance.ContainsDiagnostics;
    public Boolean ContainsDirectives => this.instance.ContainsDirectives;
    public Boolean HasLeadingTrivia => this.instance.HasLeadingTrivia;
    public Boolean HasTrailingTrivia => this.instance.HasTrailingTrivia;
    public SyntaxNode Parent => this.instance.Parent;
    public SyntaxTrivia ParentTrivia => this.instance.ParentTrivia;
    public Boolean ContainsAnnotations => this.instance.ContainsAnnotations;

    public static explicit operator BinaryPatternSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator CSharpSyntaxNode(BinaryPatternSyntaxWrapper wrapper) =>
        wrapper.instance;

    public static BinaryPatternSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new BinaryPatternSyntaxWrapper((CSharpSyntaxNode)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

    public static implicit operator PatternSyntaxWrapper(BinaryPatternSyntaxWrapper up) => PatternSyntaxWrapper.From(up.WrappedInstance);
    public static explicit operator BinaryPatternSyntaxWrapper(PatternSyntaxWrapper down) => BinaryPatternSyntaxWrapper.From(down.WrappedInstance);

    public static implicit operator ExpressionOrPatternSyntaxWrapper(BinaryPatternSyntaxWrapper up) => ExpressionOrPatternSyntaxWrapper.From(up.WrappedInstance);
    public static explicit operator BinaryPatternSyntaxWrapper(ExpressionOrPatternSyntaxWrapper down) => BinaryPatternSyntaxWrapper.From(down.WrappedInstance);

}