//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct ExtensionMemberCrefSyntaxWrapper : ISyntaxWrapper<MemberCrefSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.ExtensionMemberCrefSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(ExtensionMemberCrefSyntaxWrapper));
    private readonly MemberCrefSyntax instance;

    private ExtensionMemberCrefSyntaxWrapper(MemberCrefSyntax instance) =>
        this.instance = instance;

    [Obsolete("Use WrappedInstance instead")]
    public MemberCrefSyntax Node => this.instance;

    [Obsolete("Use WrappedInstance instead")]
    public MemberCrefSyntax SyntaxNode => this.instance;

    public MemberCrefSyntax WrappedInstance => this.instance;

    private static readonly Func<MemberCrefSyntax, SyntaxToken> ExtensionKeywordAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, SyntaxToken>(WrappedType, "ExtensionKeyword");
    public SyntaxToken ExtensionKeyword => (SyntaxToken)ExtensionKeywordAccessor(this.instance);
    private static readonly Func<MemberCrefSyntax, TypeArgumentListSyntax> TypeArgumentListAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, TypeArgumentListSyntax>(WrappedType, "TypeArgumentList");
    public TypeArgumentListSyntax TypeArgumentList => TypeArgumentListAccessor(this.instance);
    private static readonly Func<MemberCrefSyntax, CrefParameterListSyntax> ParametersAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, CrefParameterListSyntax>(WrappedType, "Parameters");
    public CrefParameterListSyntax Parameters => ParametersAccessor(this.instance);
    private static readonly Func<MemberCrefSyntax, SyntaxToken> DotTokenAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, SyntaxToken>(WrappedType, "DotToken");
    public SyntaxToken DotToken => (SyntaxToken)DotTokenAccessor(this.instance);
    private static readonly Func<MemberCrefSyntax, MemberCrefSyntax> MemberAccessor = LightupHelpers.CreatePropertyAccessor<MemberCrefSyntax, MemberCrefSyntax>(WrappedType, "Member");
    public MemberCrefSyntax Member => MemberAccessor(this.instance);
    public String Language => this.instance.Language;
    public Int32 RawKind => this.instance.RawKind;
    public TextSpan FullSpan => this.instance.FullSpan;
    public TextSpan Span => this.instance.Span;
    public Int32 SpanStart => this.instance.SpanStart;
    public Boolean IsMissing => this.instance.IsMissing;
    public Boolean IsStructuredTrivia => this.instance.IsStructuredTrivia;
    public Boolean HasStructuredTrivia => this.instance.HasStructuredTrivia;
    public Boolean ContainsSkippedText => this.instance.ContainsSkippedText;
    public Boolean ContainsDiagnostics => this.instance.ContainsDiagnostics;
    public Boolean ContainsDirectives => this.instance.ContainsDirectives;
    public Boolean HasLeadingTrivia => this.instance.HasLeadingTrivia;
    public Boolean HasTrailingTrivia => this.instance.HasTrailingTrivia;
    public SyntaxNode Parent => this.instance.Parent;
    public SyntaxTrivia ParentTrivia => this.instance.ParentTrivia;
    public Boolean ContainsAnnotations => this.instance.ContainsAnnotations;

    public static explicit operator ExtensionMemberCrefSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator MemberCrefSyntax(ExtensionMemberCrefSyntaxWrapper wrapper) =>
        wrapper.instance;

    public static ExtensionMemberCrefSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new ExtensionMemberCrefSyntaxWrapper((MemberCrefSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}