//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public static partial class ParenthesizedLambdaExpressionSyntaxShimExtensions
{
    private static readonly Type WrappedType = typeof(ParenthesizedLambdaExpressionSyntax);

    private static readonly Func<ParenthesizedLambdaExpressionSyntax, SyntaxList<AttributeListSyntax>> AttributeListsAccessor = AccessorFactory.CreateProperty<Func<ParenthesizedLambdaExpressionSyntax, SyntaxList<AttributeListSyntax>>>(WrappedType, "AttributeLists");
    private static readonly Func<ParenthesizedLambdaExpressionSyntax, BlockSyntax> BlockAccessor = AccessorFactory.CreateProperty<Func<ParenthesizedLambdaExpressionSyntax, BlockSyntax>>(WrappedType, "Block");
    private static readonly Func<ParenthesizedLambdaExpressionSyntax, ExpressionSyntax> ExpressionBodyAccessor = AccessorFactory.CreateProperty<Func<ParenthesizedLambdaExpressionSyntax, ExpressionSyntax>>(WrappedType, "ExpressionBody");
    private static readonly Func<ParenthesizedLambdaExpressionSyntax, SyntaxTokenList> ModifiersAccessor = AccessorFactory.CreateProperty<Func<ParenthesizedLambdaExpressionSyntax, SyntaxTokenList>>(WrappedType, "Modifiers");
    private static readonly Func<ParenthesizedLambdaExpressionSyntax, TypeSyntax> ReturnTypeAccessor = AccessorFactory.CreateProperty<Func<ParenthesizedLambdaExpressionSyntax, TypeSyntax>>(WrappedType, "ReturnType");

    extension(ParenthesizedLambdaExpressionSyntax wrappedInstance)
    {
        public SyntaxList<AttributeListSyntax> AttributeLists => (SyntaxList<AttributeListSyntax>)AttributeListsAccessor(wrappedInstance);
        public BlockSyntax Block => BlockAccessor(wrappedInstance);
        public ExpressionSyntax ExpressionBody => ExpressionBodyAccessor(wrappedInstance);
        public SyntaxTokenList Modifiers => (SyntaxTokenList)ModifiersAccessor(wrappedInstance);
        public TypeSyntax ReturnType => ReturnTypeAccessor(wrappedInstance);
    }
}