//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class ControlFlowGraphExtensionsEx
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphExtensions");

    private static readonly Func<ControlFlowGraphWrapper, IFlowAnonymousFunctionOperationWrapper, CancellationToken, ControlFlowGraphWrapper> GetAnonymousFunctionControlFlowGraphInScopeAccessor = AccessorFactory.CreateStaticMethod<Func<ControlFlowGraphWrapper, IFlowAnonymousFunctionOperationWrapper, CancellationToken, ControlFlowGraphWrapper>>(WrappedType, "GetAnonymousFunctionControlFlowGraphInScope");
    private static readonly Func<ControlFlowGraphWrapper, IMethodSymbol, CancellationToken, ControlFlowGraphWrapper> GetLocalFunctionControlFlowGraphInScopeAccessor = AccessorFactory.CreateStaticMethod<Func<ControlFlowGraphWrapper, IMethodSymbol, CancellationToken, ControlFlowGraphWrapper>>(WrappedType, "GetLocalFunctionControlFlowGraphInScope");

    public static ControlFlowGraphWrapper GetAnonymousFunctionControlFlowGraphInScope(this ControlFlowGraphWrapper controlFlowGraph, IFlowAnonymousFunctionOperationWrapper anonymousFunction, CancellationToken cancellationToken) => GetAnonymousFunctionControlFlowGraphInScopeAccessor(controlFlowGraph, anonymousFunction, cancellationToken);
    public static ControlFlowGraphWrapper GetLocalFunctionControlFlowGraphInScope(this ControlFlowGraphWrapper controlFlowGraph, IMethodSymbol localFunction, CancellationToken cancellationToken) => GetLocalFunctionControlFlowGraphInScopeAccessor(controlFlowGraph, localFunction, cancellationToken);
}