//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct IListPatternOperationWrapper : IOperationWrapper
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IListPatternOperation";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(IListPatternOperationWrapper));
    private readonly IOperation wrappedInstance;

    private static readonly Func<IOperation, IEnumerable<IOperation>> ChildrenAccessor = AccessorFactory.CreateProperty<Func<IOperation, IEnumerable<IOperation>>>(WrappedType, "Children");
    private static readonly Func<IOperation, ISymbol> DeclaredSymbolAccessor = AccessorFactory.CreateProperty<Func<IOperation, ISymbol>>(WrappedType, "DeclaredSymbol");
    private static readonly Func<IOperation, ISymbol> IndexerSymbolAccessor = AccessorFactory.CreateProperty<Func<IOperation, ISymbol>>(WrappedType, "IndexerSymbol");
    private static readonly Func<IOperation, ITypeSymbol> InputTypeAccessor = AccessorFactory.CreateProperty<Func<IOperation, ITypeSymbol>>(WrappedType, "InputType");
    private static readonly Func<IOperation, Boolean> IsImplicitAccessor = AccessorFactory.CreateProperty<Func<IOperation, Boolean>>(WrappedType, "IsImplicit");
    private static readonly Func<IOperation, String> LanguageAccessor = AccessorFactory.CreateProperty<Func<IOperation, String>>(WrappedType, "Language");
    private static readonly Func<IOperation, ISymbol> LengthSymbolAccessor = AccessorFactory.CreateProperty<Func<IOperation, ISymbol>>(WrappedType, "LengthSymbol");
    private static readonly Func<IOperation, ITypeSymbol> NarrowedTypeAccessor = AccessorFactory.CreateProperty<Func<IOperation, ITypeSymbol>>(WrappedType, "NarrowedType");
    private static readonly Func<IOperation, IOperation> ParentAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Parent");
    private static readonly Func<IOperation, ImmutableArray<IOperation>> PatternsAccessor = LightupHelpers.CreateOperationListPropertyAccessor<IOperation>(WrappedType, nameof(Patterns));
    private static readonly Func<IOperation, SemanticModel> SemanticModelAccessor = AccessorFactory.CreateProperty<Func<IOperation, SemanticModel>>(WrappedType, "SemanticModel");

    private IListPatternOperationWrapper(IOperation wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public IOperation WrappedOperation => wrappedInstance;

    public IOperation WrappedInstance => wrappedInstance;

    public Optional<Object> ConstantValue => wrappedInstance.ConstantValue;
    public OperationKind Kind => wrappedInstance.Kind;
    public SyntaxNode Syntax => wrappedInstance.Syntax;
    public ITypeSymbol Type => wrappedInstance.Type;

    [System.ObsoleteAttribute("This API has performance penalties, please use ChildOperations instead.", false)]
    public IEnumerable<IOperation> Children => (IEnumerable<IOperation>)ChildrenAccessor(wrappedInstance);
    public ISymbol DeclaredSymbol => (ISymbol)DeclaredSymbolAccessor(wrappedInstance);
    public ISymbol IndexerSymbol => (ISymbol)IndexerSymbolAccessor(wrappedInstance);
    public ITypeSymbol InputType => (ITypeSymbol)InputTypeAccessor(wrappedInstance);
    public Boolean IsImplicit => (Boolean)IsImplicitAccessor(wrappedInstance);
    public String Language => (String)LanguageAccessor(wrappedInstance);
    public ISymbol LengthSymbol => (ISymbol)LengthSymbolAccessor(wrappedInstance);
    public ITypeSymbol NarrowedType => (ITypeSymbol)NarrowedTypeAccessor(wrappedInstance);
    public IOperation Parent => ParentAccessor(wrappedInstance);
    public ImmutableArray<IOperation> Patterns => PatternsAccessor(wrappedInstance);
    public SemanticModel SemanticModel => (SemanticModel)SemanticModelAccessor(wrappedInstance);

    [Obsolete("Use From instead")]
    public static IListPatternOperationWrapper FromOperation(IOperation operation) =>
        From(operation);

    public static IListPatternOperationWrapper From(IOperation operation)
    {
        if (operation is null)
        {
            return default;
        }
        else if (IsInstance(operation))
        {
            return new IListPatternOperationWrapper(operation);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{operation.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(IOperation operation) =>
        operation is not null && LightupHelpers.CanWrapOperation(operation, WrappedType);

    public static implicit operator IPatternOperationWrapper(IListPatternOperationWrapper up) => IPatternOperationWrapper.From(up.WrappedInstance);
    public static explicit operator IListPatternOperationWrapper(IPatternOperationWrapper down) => IListPatternOperationWrapper.From(down.WrappedInstance);

}