//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct IFunctionPointerInvocationOperationWrapper : IOperationWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.Operations.IFunctionPointerInvocationOperation");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly IOperation wrappedInstance;

    private static readonly Func<IOperation, ImmutableArray<IArgumentOperationWrapper>> ArgumentsAccessor = AccessorFactory.CreateProperty<Func<IOperation, ImmutableArray<IArgumentOperationWrapper>>>(WrappedType, "Arguments");
    private static readonly Func<IOperation, IEnumerable<IOperation>> ChildrenAccessor = AccessorFactory.CreateProperty<Func<IOperation, IEnumerable<IOperation>>>(WrappedType, "Children");
    private static readonly Func<IOperation, bool> IsImplicitAccessor = AccessorFactory.CreateProperty<Func<IOperation, bool>>(WrappedType, "IsImplicit");
    private static readonly Func<IOperation, string> LanguageAccessor = AccessorFactory.CreateProperty<Func<IOperation, string>>(WrappedType, "Language");
    private static readonly Func<IOperation, IOperation> ParentAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Parent");
    private static readonly Func<IOperation, SemanticModel> SemanticModelAccessor = AccessorFactory.CreateProperty<Func<IOperation, SemanticModel>>(WrappedType, "SemanticModel");
    private static readonly Func<IOperation, IOperation> TargetAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Target");

    private static readonly Action<IOperation, OperationVisitorWrapper> AcceptAccessor = AccessorFactory.CreateMethod<Action<IOperation, OperationVisitorWrapper>>(WrappedType, "Accept");

    private IFunctionPointerInvocationOperationWrapper(IOperation wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public IOperation WrappedInstance => wrappedInstance;

    public Optional<Object> ConstantValue => wrappedInstance.ConstantValue;
    public OperationKind Kind => wrappedInstance.Kind;
    public SyntaxNode Syntax => wrappedInstance.Syntax;
    public ITypeSymbol Type => wrappedInstance.Type;

    public ImmutableArray<IArgumentOperationWrapper> Arguments => ArgumentsAccessor(wrappedInstance);
    [System.ObsoleteAttribute("This API has performance penalties, please use ChildOperations instead.", false)]
    public IEnumerable<IOperation> Children => (IEnumerable<IOperation>)ChildrenAccessor(wrappedInstance);
    public bool IsImplicit => (bool)IsImplicitAccessor(wrappedInstance);
    public string Language => (string)LanguageAccessor(wrappedInstance);
    public IOperation Parent => ParentAccessor(wrappedInstance);
    public SemanticModel SemanticModel => SemanticModelAccessor(wrappedInstance);
    public IOperation Target => TargetAccessor(wrappedInstance);

    public void Accept(OperationVisitorWrapper visitor) => AcceptAccessor(wrappedInstance, visitor);

    public static IFunctionPointerInvocationOperationWrapper? FromOrDefault(IOperation instance) =>
        IsInstance(instance) ? From(instance) : null;

    public static IFunctionPointerInvocationOperationWrapper From(IOperation instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new IFunctionPointerInvocationOperationWrapper((IOperation)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.Operations.IFunctionPointerInvocationOperation'");
        }
    }

    public static bool IsInstance(IOperation instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}