//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct AnalyzerConfigSetWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.AnalyzerConfigSet");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private AnalyzerConfigSetWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    public static AnalyzerConfigSetWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new AnalyzerConfigSetWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.AnalyzerConfigSet'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}