//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct SyntaxReceiverCreatorWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.SyntaxReceiverCreator");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, MethodInfo> MethodAccessor = AccessorFactory.CreateProperty<Func<Object, MethodInfo>>(WrappedType, "Method");
    private static readonly Func<Object, Object> TargetAccessor = AccessorFactory.CreateProperty<Func<Object, Object>>(WrappedType, "Target");

    private static readonly Func<Object, AsyncCallback, Object, IAsyncResult> BeginInvokeAccessor = AccessorFactory.CreateMethod<Func<Object, AsyncCallback, Object, IAsyncResult>>(WrappedType, "BeginInvoke");
    private static readonly Func<Object, Object> CloneAccessor = AccessorFactory.CreateMethod<Func<Object, Object>>(WrappedType, "Clone");
    private static readonly Func<Object, Object[], Object> DynamicInvokeAccessor = AccessorFactory.CreateMethod<Func<Object, Object[], Object>>(WrappedType, "DynamicInvoke");
    private static readonly Func<Object, IAsyncResult, Object> EndInvokeAccessor = AccessorFactory.CreateMethod<Func<Object, IAsyncResult, Object>>(WrappedType, "EndInvoke");
    private static readonly Func<Object, Delegate[]> GetInvocationListAccessor = AccessorFactory.CreateMethod<Func<Object, Delegate[]>>(WrappedType, "GetInvocationList");
    private static readonly Action<Object, SerializationInfo, StreamingContext> GetObjectDataAccessor = AccessorFactory.CreateMethod<Action<Object, SerializationInfo, StreamingContext>>(WrappedType, "GetObjectData");
    private static readonly Func<Object, Object> InvokeAccessor = AccessorFactory.CreateMethod<Func<Object, Object>>(WrappedType, "Invoke");

    private SyntaxReceiverCreatorWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    public MethodInfo Method => (MethodInfo)MethodAccessor(wrappedInstance);
    public Object Target => (Object)TargetAccessor(wrappedInstance);

    public IAsyncResult BeginInvoke(AsyncCallback callback, Object @object) => (IAsyncResult)BeginInvokeAccessor(wrappedInstance, callback, @object);
    public Object Clone() => (Object)CloneAccessor(wrappedInstance);
    public Object DynamicInvoke(Object[] args) => (Object)DynamicInvokeAccessor(wrappedInstance, args);
    public ISyntaxReceiverWrapper EndInvoke(IAsyncResult result) => ISyntaxReceiverWrapper.From(EndInvokeAccessor(wrappedInstance, result));
    public Delegate[] GetInvocationList() => (Delegate[])GetInvocationListAccessor(wrappedInstance);
    [System.ObsoleteAttribute("This API supports obsolete formatter-based serialization. It should not be called or extended by application code.")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public void GetObjectData(SerializationInfo info, StreamingContext context) => GetObjectDataAccessor(wrappedInstance, info, context);
    public ISyntaxReceiverWrapper Invoke() => ISyntaxReceiverWrapper.From(InvokeAccessor(wrappedInstance));

    public static SyntaxReceiverCreatorWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new SyntaxReceiverCreatorWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.SyntaxReceiverCreator'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}