//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct GeneratorDriverTimingInfoWrapper : IWrapper, IEquatable<GeneratorDriverTimingInfoWrapper>
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.GeneratorDriverTimingInfo");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, TimeSpan> ElapsedTimeAccessor = AccessorFactory.CreateProperty<Func<Object, TimeSpan>>(WrappedType, "ElapsedTime");
    private static readonly Func<Object, ImmutableArray<GeneratorTimingInfoWrapper>> GeneratorTimesAccessor = AccessorFactory.CreateProperty<Func<Object, ImmutableArray<GeneratorTimingInfoWrapper>>>(WrappedType, "GeneratorTimes");

    private GeneratorDriverTimingInfoWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    object IWrapper.WrappedInstance => wrappedInstance;

    public override int GetHashCode() =>
        wrappedInstance?.GetHashCode() ?? 0;

    public override bool Equals(object obj) =>
        (obj is IWrapper wrapper && Equals(wrappedInstance, wrapper.WrappedInstance))
        || Equals(wrappedInstance, obj);

    public bool Equals(GeneratorDriverTimingInfoWrapper other) =>
        Equals(wrappedInstance, other.wrappedInstance);

    public static bool operator ==(GeneratorDriverTimingInfoWrapper left, GeneratorDriverTimingInfoWrapper right) =>
        Equals(left.wrappedInstance, right.wrappedInstance);

    public static bool operator !=(GeneratorDriverTimingInfoWrapper left, GeneratorDriverTimingInfoWrapper right) =>
        !Equals(left.wrappedInstance, right.wrappedInstance);

    public TimeSpan ElapsedTime => ElapsedTimeAccessor(wrappedInstance);
    public ImmutableArray<GeneratorTimingInfoWrapper> GeneratorTimes => GeneratorTimesAccessor(wrappedInstance);

    public static GeneratorDriverTimingInfoWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new GeneratorDriverTimingInfoWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.GeneratorDriverTimingInfo'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}