//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;

namespace SonarAnalyzer.ShimLayer;

public static partial class SymbolDisplayFormatShimExtensions
{
    private static readonly Type WrappedType = typeof(SymbolDisplayFormat);

    private static readonly Func<SymbolDisplayFormat, SymbolDisplayGenericsOptions, SymbolDisplayFormat> RemoveGenericsOptionsAccessor = AccessorFactory.CreateMethod<Func<SymbolDisplayFormat, SymbolDisplayGenericsOptions, SymbolDisplayFormat>>(WrappedType, "RemoveGenericsOptions");
    private static readonly Func<SymbolDisplayFormat, SymbolDisplayLocalOptions, SymbolDisplayFormat> RemoveLocalOptionsAccessor = AccessorFactory.CreateMethod<Func<SymbolDisplayFormat, SymbolDisplayLocalOptions, SymbolDisplayFormat>>(WrappedType, "RemoveLocalOptions");
    private static readonly Func<SymbolDisplayFormat, SymbolDisplayMiscellaneousOptions, SymbolDisplayFormat> RemoveMiscellaneousOptionsAccessor = AccessorFactory.CreateMethod<Func<SymbolDisplayFormat, SymbolDisplayMiscellaneousOptions, SymbolDisplayFormat>>(WrappedType, "RemoveMiscellaneousOptions");

    extension(SymbolDisplayFormat wrappedInstance)
    {
        public SymbolDisplayFormat RemoveGenericsOptions(SymbolDisplayGenericsOptions options) => RemoveGenericsOptionsAccessor(wrappedInstance, options);
        public SymbolDisplayFormat RemoveLocalOptions(SymbolDisplayLocalOptions options) => RemoveLocalOptionsAccessor(wrappedInstance, options);
        public SymbolDisplayFormat RemoveMiscellaneousOptions(SymbolDisplayMiscellaneousOptions options) => RemoveMiscellaneousOptionsAccessor(wrappedInstance, options);
    }
}