//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;

namespace SonarAnalyzer.ShimLayer;

public static partial class ITypeSymbolShimExtensions
{
    private static readonly Type WrappedType = typeof(ITypeSymbol);

    private static readonly Func<ITypeSymbol, IParameterSymbol> ExtensionParameterAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, IParameterSymbol>>(WrappedType, "ExtensionParameter");
    private static readonly Func<ITypeSymbol, bool> IsExtensionAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsExtension");
    private static readonly Func<ITypeSymbol, bool> IsNativeIntegerTypeAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsNativeIntegerType");
    private static readonly Func<ITypeSymbol, bool> IsReadOnlyAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsReadOnly");
    private static readonly Func<ITypeSymbol, bool> IsRecordAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsRecord");
    private static readonly Func<ITypeSymbol, bool> IsRefLikeTypeAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsRefLikeType");
    private static readonly Func<ITypeSymbol, bool> IsTupleTypeAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsTupleType");
    private static readonly Func<ITypeSymbol, bool> IsUnmanagedTypeAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, bool>>(WrappedType, "IsUnmanagedType");
    private static readonly Func<ITypeSymbol, int> MetadataTokenAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, int>>(WrappedType, "MetadataToken");
    private static readonly Func<ITypeSymbol, NullableAnnotation> NullableAnnotationAccessor = AccessorFactory.CreateProperty<Func<ITypeSymbol, NullableAnnotation>>(WrappedType, "NullableAnnotation");

    private static readonly Func<ITypeSymbol, NullableFlowState, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>> ToDisplayPartsAccessor = AccessorFactory.CreateMethod<Func<ITypeSymbol, NullableFlowState, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>>>(WrappedType, "ToDisplayParts");
    private static readonly Func<ITypeSymbol, NullableFlowState, SymbolDisplayFormat, string> ToDisplayStringAccessor = AccessorFactory.CreateMethod<Func<ITypeSymbol, NullableFlowState, SymbolDisplayFormat, string>>(WrappedType, "ToDisplayString");
    private static readonly Func<ITypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>> ToMinimalDisplayPartsAccessor = AccessorFactory.CreateMethod<Func<ITypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>>>(WrappedType, "ToMinimalDisplayParts");
    private static readonly Func<ITypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, string> ToMinimalDisplayStringAccessor = AccessorFactory.CreateMethod<Func<ITypeSymbol, SemanticModel, NullableFlowState, int, SymbolDisplayFormat, string>>(WrappedType, "ToMinimalDisplayString");
    private static readonly Func<ITypeSymbol, NullableAnnotation, ITypeSymbol> WithNullableAnnotationAccessor = AccessorFactory.CreateMethod<Func<ITypeSymbol, NullableAnnotation, ITypeSymbol>>(WrappedType, "WithNullableAnnotation");

    extension(ITypeSymbol wrappedInstance)
    {
        [System.ObsoleteAttribute("This API will be removed in the future. Use INamedTypeSymbol.ExtensionParameter instead.")]
        public IParameterSymbol ExtensionParameter => ExtensionParameterAccessor(wrappedInstance);
        [System.ObsoleteAttribute("This API will be removed in the future. Use INamedTypeSymbol.IsExtension instead.")]
        public bool IsExtension => (bool)IsExtensionAccessor(wrappedInstance);
        public bool IsNativeIntegerType => (bool)IsNativeIntegerTypeAccessor(wrappedInstance);
        public bool IsReadOnly => (bool)IsReadOnlyAccessor(wrappedInstance);
        public bool IsRecord => (bool)IsRecordAccessor(wrappedInstance);
        public bool IsRefLikeType => (bool)IsRefLikeTypeAccessor(wrappedInstance);
        public bool IsTupleType => (bool)IsTupleTypeAccessor(wrappedInstance);
        public bool IsUnmanagedType => (bool)IsUnmanagedTypeAccessor(wrappedInstance);
        public int MetadataToken => (int)MetadataTokenAccessor(wrappedInstance);
        public NullableAnnotation NullableAnnotation => (NullableAnnotation)NullableAnnotationAccessor(wrappedInstance);

        public ImmutableArray<SymbolDisplayPart> ToDisplayParts(NullableFlowState topLevelNullability, SymbolDisplayFormat format) => (ImmutableArray<SymbolDisplayPart>)ToDisplayPartsAccessor(wrappedInstance, topLevelNullability, format);
        public string ToDisplayString(NullableFlowState topLevelNullability, SymbolDisplayFormat format) => (string)ToDisplayStringAccessor(wrappedInstance, topLevelNullability, format);
        public ImmutableArray<SymbolDisplayPart> ToMinimalDisplayParts(SemanticModel semanticModel, NullableFlowState topLevelNullability, int position, SymbolDisplayFormat format) => (ImmutableArray<SymbolDisplayPart>)ToMinimalDisplayPartsAccessor(wrappedInstance, semanticModel, topLevelNullability, position, format);
        public string ToMinimalDisplayString(SemanticModel semanticModel, NullableFlowState topLevelNullability, int position, SymbolDisplayFormat format) => (string)ToMinimalDisplayStringAccessor(wrappedInstance, semanticModel, topLevelNullability, position, format);
        public ITypeSymbol WithNullableAnnotation(NullableAnnotation nullableAnnotation) => WithNullableAnnotationAccessor(wrappedInstance, nullableAnnotation);
    }
}