//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis.CSharp;

namespace SonarAnalyzer.ShimLayer;

public static partial class CSharpSyntaxTreeShimExtensions
{
    private static readonly Type WrappedType = typeof(CSharpSyntaxTree);

    private static readonly Func<CSharpSyntaxTree, ImmutableDictionary<string, ReportDiagnostic>> DiagnosticOptionsAccessor = AccessorFactory.CreateProperty<Func<CSharpSyntaxTree, ImmutableDictionary<string, ReportDiagnostic>>>(WrappedType, "DiagnosticOptions");

    private static readonly Func<CSharpSyntaxTree, CSharpSyntaxNode, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, SyntaxTree> CreateAccessor_Overload2 = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, CSharpSyntaxNode, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, SyntaxTree>>(WrappedType, "Create");
    private static readonly Func<CSharpSyntaxTree, CSharpSyntaxNode, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, Nullable<bool>, SyntaxTree> CreateAccessor_Overload3 = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, CSharpSyntaxNode, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, Nullable<bool>, SyntaxTree>>(WrappedType, "Create");
    private static readonly Func<CSharpSyntaxTree, SourceText, CSharpParseOptions, string, ImmutableDictionary<string, ReportDiagnostic>, Nullable<bool>, CancellationToken, SyntaxTree> ParseTextAccessor = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, SourceText, CSharpParseOptions, string, ImmutableDictionary<string, ReportDiagnostic>, Nullable<bool>, CancellationToken, SyntaxTree>>(WrappedType, "ParseText");
    private static readonly Func<CSharpSyntaxTree, SourceText, CSharpParseOptions, string, ImmutableDictionary<string, ReportDiagnostic>, CancellationToken, SyntaxTree> ParseTextAccessor_Overload2 = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, SourceText, CSharpParseOptions, string, ImmutableDictionary<string, ReportDiagnostic>, CancellationToken, SyntaxTree>>(WrappedType, "ParseText");
    private static readonly Func<CSharpSyntaxTree, string, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, Nullable<bool>, CancellationToken, SyntaxTree> ParseTextAccessor_Overload4 = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, string, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, Nullable<bool>, CancellationToken, SyntaxTree>>(WrappedType, "ParseText");
    private static readonly Func<CSharpSyntaxTree, string, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, CancellationToken, SyntaxTree> ParseTextAccessor_Overload5 = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, string, CSharpParseOptions, string, Encoding, ImmutableDictionary<string, ReportDiagnostic>, CancellationToken, SyntaxTree>>(WrappedType, "ParseText");
    private static readonly Func<CSharpSyntaxTree, ImmutableDictionary<string, ReportDiagnostic>, SyntaxTree> WithDiagnosticOptionsAccessor = AccessorFactory.CreateMethod<Func<CSharpSyntaxTree, ImmutableDictionary<string, ReportDiagnostic>, SyntaxTree>>(WrappedType, "WithDiagnosticOptions");

    extension(CSharpSyntaxTree wrappedInstance)
    {
        [System.ObsoleteAttribute("Obsolete due to performance problems, use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public ImmutableDictionary<string, ReportDiagnostic> DiagnosticOptions => (ImmutableDictionary<string, ReportDiagnostic>)DiagnosticOptionsAccessor(wrappedInstance);

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ObsoleteAttribute("The diagnosticOptions parameter is obsolete due to performance problems, if you are passing non-null use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree Create(CSharpSyntaxNode root, CSharpParseOptions options, string path, Encoding encoding, ImmutableDictionary<string, ReportDiagnostic> diagnosticOptions) => CreateAccessor_Overload2(wrappedInstance, root, options, path, encoding, diagnosticOptions);
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ObsoleteAttribute("The diagnosticOptions and isGeneratedCode parameters are obsolete due to performance problems, if you are using them use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree Create(CSharpSyntaxNode root, CSharpParseOptions options, string path, Encoding encoding, ImmutableDictionary<string, ReportDiagnostic> diagnosticOptions, Nullable<bool> isGeneratedCode) => CreateAccessor_Overload3(wrappedInstance, root, options, path, encoding, diagnosticOptions, isGeneratedCode);
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ObsoleteAttribute("The diagnosticOptions and isGeneratedCode parameters are obsolete due to performance problems, if you are using them use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree ParseText(SourceText text, CSharpParseOptions options, string path, ImmutableDictionary<string, ReportDiagnostic> diagnosticOptions, Nullable<bool> isGeneratedCode, CancellationToken cancellationToken) => ParseTextAccessor(wrappedInstance, text, options, path, diagnosticOptions, isGeneratedCode, cancellationToken);
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ObsoleteAttribute("The diagnosticOptions parameter is obsolete due to performance problems, if you are passing non-null use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree ParseText(SourceText text, CSharpParseOptions options, string path, ImmutableDictionary<string, ReportDiagnostic> diagnosticOptions, CancellationToken cancellationToken) => ParseTextAccessor_Overload2(wrappedInstance, text, options, path, diagnosticOptions, cancellationToken);
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ObsoleteAttribute("The diagnosticOptions and isGeneratedCode parameters are obsolete due to performance problems, if you are using them use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree ParseText(string text, CSharpParseOptions options, string path, Encoding encoding, ImmutableDictionary<string, ReportDiagnostic> diagnosticOptions, Nullable<bool> isGeneratedCode, CancellationToken cancellationToken) => ParseTextAccessor_Overload4(wrappedInstance, text, options, path, encoding, diagnosticOptions, isGeneratedCode, cancellationToken);
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ObsoleteAttribute("The diagnosticOptions parameter is obsolete due to performance problems, if you are passing non-null use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree ParseText(string text, CSharpParseOptions options, string path, Encoding encoding, ImmutableDictionary<string, ReportDiagnostic> diagnosticOptions, CancellationToken cancellationToken) => ParseTextAccessor_Overload5(wrappedInstance, text, options, path, encoding, diagnosticOptions, cancellationToken);
        [System.ObsoleteAttribute("Obsolete due to performance problems, use CompilationOptions.SyntaxTreeOptionsProvider instead", false)]
        public SyntaxTree WithDiagnosticOptions(ImmutableDictionary<string, ReportDiagnostic> options) => WithDiagnosticOptionsAccessor(wrappedInstance, options);
    }
}