//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class SemanticModelShimExtensions
{
    private static readonly Type WrappedType = typeof(SemanticModel);

    private static readonly Func<SemanticModel, int, CancellationToken, ImmutableArray<IImportScopeWrapper>> GetImportScopesAccessor = AccessorFactory.CreateMethod<Func<SemanticModel, int, CancellationToken, ImmutableArray<IImportScopeWrapper>>>(WrappedType, "GetImportScopes");
    private static readonly Func<SemanticModel, int, NullableContext> GetNullableContextAccessor = AccessorFactory.CreateMethod<Func<SemanticModel, int, NullableContext>>(WrappedType, "GetNullableContext");

    extension(SemanticModel wrappedInstance)
    {
        public ImmutableArray<IImportScopeWrapper> GetImportScopes(int position, CancellationToken cancellationToken) => GetImportScopesAccessor(wrappedInstance, position, cancellationToken);
        public NullableContext GetNullableContext(int position) => (NullableContext)GetNullableContextAccessor(wrappedInstance, position);
    }
}