//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using CSharpExtensions = Microsoft.CodeAnalysis.CSharp.CSharpExtensions;

namespace SonarAnalyzer.ShimLayer;

public static class LanguageVersionFactsEx
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.CSharp.LanguageVersionFacts");

    private static readonly Func<LanguageVersion, LanguageVersion> MapSpecifiedToEffectiveVersionAccessor = AccessorFactory.CreateStaticMethod<Func<LanguageVersion, LanguageVersion>>(WrappedType, "MapSpecifiedToEffectiveVersion");
    private static readonly Func<LanguageVersion, string> ToDisplayStringAccessor = AccessorFactory.CreateStaticMethod<Func<LanguageVersion, string>>(WrappedType, "ToDisplayString");
    private delegate bool TryParseAccessorDelegate(string version, out LanguageVersion result);
    private static readonly TryParseAccessorDelegate TryParseAccessor = AccessorFactory.CreateStaticMethod<TryParseAccessorDelegate>(WrappedType, "TryParse");

    public static LanguageVersion MapSpecifiedToEffectiveVersion(this LanguageVersion version) => (LanguageVersion)MapSpecifiedToEffectiveVersionAccessor(version);
    public static string ToDisplayString(this LanguageVersion version) => (string)ToDisplayStringAccessor(version);
    public static bool TryParse(string version, out LanguageVersion result) => (bool)TryParseAccessor(version, out result);
}