//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct GeneratorAttributeWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.GeneratorAttribute");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, string[]> LanguagesAccessor = AccessorFactory.CreateProperty<Func<Object, string[]>>(WrappedType, "Languages");
    private static readonly Func<Object, Object> TypeIdAccessor = AccessorFactory.CreateProperty<Func<Object, Object>>(WrappedType, "TypeId");

    private static readonly Func<Object, bool> IsDefaultAttributeAccessor = AccessorFactory.CreateMethod<Func<Object, bool>>(WrappedType, "IsDefaultAttribute");
    private static readonly Func<Object, Object, bool> MatchAccessor = AccessorFactory.CreateMethod<Func<Object, Object, bool>>(WrappedType, "Match");

    private GeneratorAttributeWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    public string[] Languages => (string[])LanguagesAccessor(wrappedInstance);
    public Object TypeId => (Object)TypeIdAccessor(wrappedInstance);

    public bool IsDefaultAttribute() => (bool)IsDefaultAttributeAccessor(wrappedInstance);
    public bool Match(Object obj) => (bool)MatchAccessor(wrappedInstance, obj);

    public static GeneratorAttributeWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new GeneratorAttributeWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.GeneratorAttribute'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}