//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

internal readonly partial struct IInterpolatedStringTextOperationWrapper : IOperationWrapper
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IInterpolatedStringTextOperation";
    private static readonly Type WrappedType;

    private readonly IOperation operation;

    static IInterpolatedStringTextOperationWrapper()
    {
        WrappedType = TypeRegister.LatestType(typeof(IInterpolatedStringTextOperationWrapper));
    }

    private IInterpolatedStringTextOperationWrapper(IOperation operation) =>
        this.operation = operation;

    [Obsolete("Use WrappedInstance instead")]
    public IOperation WrappedOperation => this.operation;

    public IOperation WrappedInstance => this.operation;

    [Obsolete("Use From instead")]
    public static IInterpolatedStringTextOperationWrapper FromOperation(IOperation operation) =>
        From(operation);

    public static IInterpolatedStringTextOperationWrapper From(IOperation operation)
    {
        if (operation is null)
        {
            return default;
        }
        else if (IsInstance(operation))
        {
            return new IInterpolatedStringTextOperationWrapper(operation);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{operation.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(IOperation operation) =>
        operation is not null && LightupHelpers.CanWrapOperation(operation, WrappedType);

    public static implicit operator IInterpolatedStringContentOperationWrapper(IInterpolatedStringTextOperationWrapper up) => IInterpolatedStringContentOperationWrapper.From(up.WrappedInstance);
    public static explicit operator IInterpolatedStringTextOperationWrapper(IInterpolatedStringContentOperationWrapper down) => IInterpolatedStringTextOperationWrapper.From(down.WrappedInstance);

}