//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;

namespace SonarAnalyzer.ShimLayer;

public static partial class ParseOptionsShimExtensions
{
    private static readonly Type WrappedType = typeof(ParseOptions);

    private static readonly Func<ParseOptions, ImmutableArray<Diagnostic>> ErrorsAccessor = AccessorFactory.CreateProperty<Func<ParseOptions, ImmutableArray<Diagnostic>>>(WrappedType, "Errors");
    private static readonly Func<ParseOptions, string> LanguageAccessor = AccessorFactory.CreateProperty<Func<ParseOptions, string>>(WrappedType, "Language");
    private static readonly Func<ParseOptions, SourceCodeKind> SpecifiedKindAccessor = AccessorFactory.CreateProperty<Func<ParseOptions, SourceCodeKind>>(WrappedType, "SpecifiedKind");

    extension(ParseOptions wrappedInstance)
    {
        public ImmutableArray<Diagnostic> Errors => (ImmutableArray<Diagnostic>)ErrorsAccessor(wrappedInstance);
        public string Language => (string)LanguageAccessor(wrappedInstance);
        public SourceCodeKind SpecifiedKind => (SourceCodeKind)SpecifiedKindAccessor(wrappedInstance);
    }
}