//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) 2014-2025 SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct ParenthesizedPatternSyntaxWrapper: ISyntaxWrapper<CSharpSyntaxNode>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedPatternSyntax";
    private static readonly Type WrappedType;

    private readonly CSharpSyntaxNode node;

    static ParenthesizedPatternSyntaxWrapper()
    {
        WrappedType = SyntaxNodeTypes.LatestType(typeof(ParenthesizedPatternSyntaxWrapper));
        OpenParenTokenAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<CSharpSyntaxNode, SyntaxToken>(WrappedType, "OpenParenToken");
        PatternAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<CSharpSyntaxNode, CSharpSyntaxNode>(WrappedType, "Pattern");
        CloseParenTokenAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<CSharpSyntaxNode, SyntaxToken>(WrappedType, "CloseParenToken");
    }

    private ParenthesizedPatternSyntaxWrapper(CSharpSyntaxNode node) =>
        this.node = node;

    public CSharpSyntaxNode Node => this.node;

    [Obsolete("Use Node instead")]
    public CSharpSyntaxNode SyntaxNode => this.node;

    private static readonly Func<CSharpSyntaxNode, SyntaxToken> OpenParenTokenAccessor;
    public SyntaxToken OpenParenToken => (SyntaxToken)OpenParenTokenAccessor(this.node);
    private static readonly Func<CSharpSyntaxNode, CSharpSyntaxNode> PatternAccessor;
    public PatternSyntaxWrapper Pattern => (PatternSyntaxWrapper)PatternAccessor(this.node);
    private static readonly Func<CSharpSyntaxNode, SyntaxToken> CloseParenTokenAccessor;
    public SyntaxToken CloseParenToken => (SyntaxToken)CloseParenTokenAccessor(this.node);
    public String Language => this.node.Language;
    public Int32 RawKind => this.node.RawKind;
    public TextSpan FullSpan => this.node.FullSpan;
    public TextSpan Span => this.node.Span;
    public Int32 SpanStart => this.node.SpanStart;
    public Boolean IsMissing => this.node.IsMissing;
    public Boolean IsStructuredTrivia => this.node.IsStructuredTrivia;
    public Boolean HasStructuredTrivia => this.node.HasStructuredTrivia;
    public Boolean ContainsSkippedText => this.node.ContainsSkippedText;
    public Boolean ContainsDiagnostics => this.node.ContainsDiagnostics;
    public Boolean ContainsDirectives => this.node.ContainsDirectives;
    public Boolean HasLeadingTrivia => this.node.HasLeadingTrivia;
    public Boolean HasTrailingTrivia => this.node.HasTrailingTrivia;
    public SyntaxNode Parent => this.node.Parent;
    public SyntaxTrivia ParentTrivia => this.node.ParentTrivia;
    public Boolean ContainsAnnotations => this.node.ContainsAnnotations;

    public static explicit operator ParenthesizedPatternSyntaxWrapper(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }

        if (!IsInstance(node))
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }

        return new ParenthesizedPatternSyntaxWrapper((CSharpSyntaxNode)node);
    }

    public static implicit operator CSharpSyntaxNode(ParenthesizedPatternSyntaxWrapper wrapper) =>
        wrapper.node;

    public static implicit operator PatternSyntaxWrapper(ParenthesizedPatternSyntaxWrapper up) => (PatternSyntaxWrapper)up.SyntaxNode;
    public static explicit operator ParenthesizedPatternSyntaxWrapper(PatternSyntaxWrapper down) => (ParenthesizedPatternSyntaxWrapper)down.SyntaxNode;

    public static implicit operator ExpressionOrPatternSyntaxWrapper(ParenthesizedPatternSyntaxWrapper up) => (ExpressionOrPatternSyntaxWrapper)up.SyntaxNode;
    public static explicit operator ParenthesizedPatternSyntaxWrapper(ExpressionOrPatternSyntaxWrapper down) => (ParenthesizedPatternSyntaxWrapper)down.SyntaxNode;

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);
}