//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct ExtensionBlockDeclarationSyntaxWrapper : ISyntaxWrapper<TypeDeclarationSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.ExtensionBlockDeclarationSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(ExtensionBlockDeclarationSyntaxWrapper));
    private readonly TypeDeclarationSyntax wrappedInstance;

    private ExtensionBlockDeclarationSyntaxWrapper(TypeDeclarationSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public TypeDeclarationSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public TypeDeclarationSyntax SyntaxNode => wrappedInstance;

    public TypeDeclarationSyntax WrappedInstance => wrappedInstance;

    public SyntaxToken Identifier => wrappedInstance.Identifier;
    public BaseListSyntax BaseList => wrappedInstance.BaseList;
    public SyntaxList<AttributeListSyntax> AttributeLists => wrappedInstance.AttributeLists;
    public SyntaxTokenList Modifiers => wrappedInstance.Modifiers;
    public SyntaxToken Keyword => wrappedInstance.Keyword;
    public TypeParameterListSyntax TypeParameterList => wrappedInstance.TypeParameterList;
    private static readonly Func<TypeDeclarationSyntax, ParameterListSyntax> ParameterListAccessor = LightupHelpers.CreatePropertyAccessor<TypeDeclarationSyntax, ParameterListSyntax>(WrappedType, "ParameterList");
    public ParameterListSyntax ParameterList => ParameterListAccessor(wrappedInstance);
    public SyntaxList<TypeParameterConstraintClauseSyntax> ConstraintClauses => wrappedInstance.ConstraintClauses;
    public SyntaxToken OpenBraceToken => wrappedInstance.OpenBraceToken;
    public SyntaxList<MemberDeclarationSyntax> Members => wrappedInstance.Members;
    public SyntaxToken CloseBraceToken => wrappedInstance.CloseBraceToken;
    public SyntaxToken SemicolonToken => wrappedInstance.SemicolonToken;
    public Int32 Arity => wrappedInstance.Arity;
    public String Language => wrappedInstance.Language;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;

    public static explicit operator ExtensionBlockDeclarationSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator TypeDeclarationSyntax(ExtensionBlockDeclarationSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static ExtensionBlockDeclarationSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new ExtensionBlockDeclarationSyntaxWrapper((TypeDeclarationSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}