//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SonarAnalyzer.ShimLayer;

public static partial class NameSyntaxShimExtensions
{
    private static readonly Type WrappedType = typeof(NameSyntax);

    private static readonly Func<NameSyntax, bool> IsNintAccessor = AccessorFactory.CreateProperty<Func<NameSyntax, bool>>(WrappedType, "IsNint");
    private static readonly Func<NameSyntax, bool> IsNotNullAccessor = AccessorFactory.CreateProperty<Func<NameSyntax, bool>>(WrappedType, "IsNotNull");
    private static readonly Func<NameSyntax, bool> IsNuintAccessor = AccessorFactory.CreateProperty<Func<NameSyntax, bool>>(WrappedType, "IsNuint");
    private static readonly Func<NameSyntax, bool> IsUnmanagedAccessor = AccessorFactory.CreateProperty<Func<NameSyntax, bool>>(WrappedType, "IsUnmanaged");

    private static readonly Func<NameSyntax, int, bool> ContainsDirectiveAccessor = AccessorFactory.CreateMethod<Func<NameSyntax, int, bool>>(WrappedType, "ContainsDirective");
    private static readonly Func<NameSyntax, SyntaxNode, bool> IsIncrementallyIdenticalToAccessor = AccessorFactory.CreateMethod<Func<NameSyntax, SyntaxNode, bool>>(WrappedType, "IsIncrementallyIdenticalTo");

    extension(NameSyntax wrappedInstance)
    {
        public bool IsNint => (bool)IsNintAccessor(wrappedInstance);
        public bool IsNotNull => (bool)IsNotNullAccessor(wrappedInstance);
        public bool IsNuint => (bool)IsNuintAccessor(wrappedInstance);
        public bool IsUnmanaged => (bool)IsUnmanagedAccessor(wrappedInstance);

        public bool ContainsDirective(int rawKind) => (bool)ContainsDirectiveAccessor(wrappedInstance, rawKind);
        public bool IsIncrementallyIdenticalTo(SyntaxNode other) => (bool)IsIncrementallyIdenticalToAccessor(wrappedInstance, other);
    }
}