//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis.Diagnostics;

namespace SonarAnalyzer.ShimLayer;

public static partial class AnalysisContextShimExtensions
{
    private static readonly Type WrappedType = typeof(AnalysisContext);

    private static readonly Func<AnalysisContext, DiagnosticSeverity> MinimumReportedSeverityAccessor = AccessorFactory.CreateProperty<Func<AnalysisContext, DiagnosticSeverity>>(WrappedType, "MinimumReportedSeverity");

    extension(AnalysisContext wrappedInstance)
    {
        public DiagnosticSeverity MinimumReportedSeverity => (DiagnosticSeverity)MinimumReportedSeverityAccessor(wrappedInstance);
    }
}