//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct BaseNamespaceDeclarationSyntaxWrapper : ISyntaxWrapper<MemberDeclarationSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.BaseNamespaceDeclarationSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(BaseNamespaceDeclarationSyntaxWrapper));
    private readonly MemberDeclarationSyntax wrappedInstance;

    private static readonly Func<MemberDeclarationSyntax, SyntaxList<AttributeListSyntax>> AttributeListsAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, SyntaxList<AttributeListSyntax>>>(WrappedType, "AttributeLists");
    private static readonly Func<MemberDeclarationSyntax, SyntaxList<ExternAliasDirectiveSyntax>> ExternsAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, SyntaxList<ExternAliasDirectiveSyntax>>>(WrappedType, "Externs");
    private static readonly Func<MemberDeclarationSyntax, SyntaxList<MemberDeclarationSyntax>> MembersAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, SyntaxList<MemberDeclarationSyntax>>>(WrappedType, "Members");
    private static readonly Func<MemberDeclarationSyntax, SyntaxTokenList> ModifiersAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, SyntaxTokenList>>(WrappedType, "Modifiers");
    private static readonly Func<MemberDeclarationSyntax, NameSyntax> NameAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, NameSyntax>>(WrappedType, "Name");
    private static readonly Func<MemberDeclarationSyntax, SyntaxToken> NamespaceKeywordAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, SyntaxToken>>(WrappedType, "NamespaceKeyword");
    private static readonly Func<MemberDeclarationSyntax, SyntaxList<UsingDirectiveSyntax>> UsingsAccessor = AccessorFactory.CreateProperty<Func<MemberDeclarationSyntax, SyntaxList<UsingDirectiveSyntax>>>(WrappedType, "Usings");

    private BaseNamespaceDeclarationSyntaxWrapper(MemberDeclarationSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public MemberDeclarationSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public MemberDeclarationSyntax SyntaxNode => wrappedInstance;

    public MemberDeclarationSyntax WrappedInstance => wrappedInstance;

    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public String Language => wrappedInstance.Language;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;

    public SyntaxList<AttributeListSyntax> AttributeLists => (SyntaxList<AttributeListSyntax>)AttributeListsAccessor(wrappedInstance);
    public SyntaxList<ExternAliasDirectiveSyntax> Externs => (SyntaxList<ExternAliasDirectiveSyntax>)ExternsAccessor(wrappedInstance);
    public SyntaxList<MemberDeclarationSyntax> Members => (SyntaxList<MemberDeclarationSyntax>)MembersAccessor(wrappedInstance);
    public SyntaxTokenList Modifiers => (SyntaxTokenList)ModifiersAccessor(wrappedInstance);
    public NameSyntax Name => NameAccessor(wrappedInstance);
    public SyntaxToken NamespaceKeyword => (SyntaxToken)NamespaceKeywordAccessor(wrappedInstance);
    public SyntaxList<UsingDirectiveSyntax> Usings => (SyntaxList<UsingDirectiveSyntax>)UsingsAccessor(wrappedInstance);

    public static explicit operator BaseNamespaceDeclarationSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator MemberDeclarationSyntax(BaseNamespaceDeclarationSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static BaseNamespaceDeclarationSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new BaseNamespaceDeclarationSyntaxWrapper((MemberDeclarationSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}