//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct CommonConversionWrapper : IWrapper, IEquatable<CommonConversionWrapper>
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.Operations.CommonConversion");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, ITypeSymbol> ConstrainedToTypeAccessor = AccessorFactory.CreateProperty<Func<Object, ITypeSymbol>>(WrappedType, "ConstrainedToType");
    private static readonly Func<Object, bool> ExistsAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "Exists");
    private static readonly Func<Object, bool> IsIdentityAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsIdentity");
    private static readonly Func<Object, bool> IsImplicitAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsImplicit");
    private static readonly Func<Object, bool> IsNullableAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsNullable");
    private static readonly Func<Object, bool> IsNumericAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsNumeric");
    private static readonly Func<Object, bool> IsReferenceAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsReference");
    private static readonly Func<Object, bool> IsUserDefinedAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsUserDefined");
    private static readonly Func<Object, IMethodSymbol> MethodSymbolAccessor = AccessorFactory.CreateProperty<Func<Object, IMethodSymbol>>(WrappedType, "MethodSymbol");

    private CommonConversionWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    object IWrapper.WrappedInstance => wrappedInstance;

    public override int GetHashCode() =>
        wrappedInstance?.GetHashCode() ?? 0;

    public override bool Equals(object obj) =>
        (obj is IWrapper wrapper && Equals(wrappedInstance, wrapper.WrappedInstance))
        || Equals(wrappedInstance, obj);

    public bool Equals(CommonConversionWrapper other) =>
        Equals(wrappedInstance, other.wrappedInstance);

    public static bool operator ==(CommonConversionWrapper left, CommonConversionWrapper right) =>
        Equals(left.wrappedInstance, right.wrappedInstance);

    public static bool operator !=(CommonConversionWrapper left, CommonConversionWrapper right) =>
        !Equals(left.wrappedInstance, right.wrappedInstance);

    public ITypeSymbol ConstrainedToType => ConstrainedToTypeAccessor(wrappedInstance);
    public bool Exists => ExistsAccessor(wrappedInstance);
    public bool IsIdentity => IsIdentityAccessor(wrappedInstance);
    public bool IsImplicit => IsImplicitAccessor(wrappedInstance);
    public bool IsNullable => IsNullableAccessor(wrappedInstance);
    public bool IsNumeric => IsNumericAccessor(wrappedInstance);
    public bool IsReference => IsReferenceAccessor(wrappedInstance);
    public bool IsUserDefined => IsUserDefinedAccessor(wrappedInstance);
    public IMethodSymbol MethodSymbol => MethodSymbolAccessor(wrappedInstance);

    public static CommonConversionWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new CommonConversionWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.Operations.CommonConversion'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}