//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct IInterpolationOperationWrapper : IOperationWrapper
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IInterpolationOperation";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(IInterpolationOperationWrapper));
    private readonly IOperation wrappedInstance;

    private static readonly Func<IOperation, IOperation> AlignmentAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Alignment");
    private static readonly Func<IOperation, IEnumerable<IOperation>> ChildrenAccessor = AccessorFactory.CreateProperty<Func<IOperation, IEnumerable<IOperation>>>(WrappedType, "Children");
    private static readonly Func<IOperation, IOperation> ExpressionAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Expression");
    private static readonly Func<IOperation, IOperation> FormatStringAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "FormatString");
    private static readonly Func<IOperation, Boolean> IsImplicitAccessor = AccessorFactory.CreateProperty<Func<IOperation, Boolean>>(WrappedType, "IsImplicit");
    private static readonly Func<IOperation, String> LanguageAccessor = AccessorFactory.CreateProperty<Func<IOperation, String>>(WrappedType, "Language");
    private static readonly Func<IOperation, IOperation> ParentAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Parent");
    private static readonly Func<IOperation, SemanticModel> SemanticModelAccessor = AccessorFactory.CreateProperty<Func<IOperation, SemanticModel>>(WrappedType, "SemanticModel");

    private IInterpolationOperationWrapper(IOperation wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public IOperation WrappedOperation => wrappedInstance;

    public IOperation WrappedInstance => wrappedInstance;

    public Optional<Object> ConstantValue => wrappedInstance.ConstantValue;
    public OperationKind Kind => wrappedInstance.Kind;
    public SyntaxNode Syntax => wrappedInstance.Syntax;
    public ITypeSymbol Type => wrappedInstance.Type;

    public IOperation Alignment => AlignmentAccessor(wrappedInstance);
    [System.ObsoleteAttribute("This API has performance penalties, please use ChildOperations instead.", false)]
    public IEnumerable<IOperation> Children => (IEnumerable<IOperation>)ChildrenAccessor(wrappedInstance);
    public IOperation Expression => ExpressionAccessor(wrappedInstance);
    public IOperation FormatString => FormatStringAccessor(wrappedInstance);
    public Boolean IsImplicit => (Boolean)IsImplicitAccessor(wrappedInstance);
    public String Language => (String)LanguageAccessor(wrappedInstance);
    public IOperation Parent => ParentAccessor(wrappedInstance);
    public SemanticModel SemanticModel => (SemanticModel)SemanticModelAccessor(wrappedInstance);

    [Obsolete("Use From instead")]
    public static IInterpolationOperationWrapper FromOperation(IOperation operation) =>
        From(operation);

    public static IInterpolationOperationWrapper From(IOperation operation)
    {
        if (operation is null)
        {
            return default;
        }
        else if (IsInstance(operation))
        {
            return new IInterpolationOperationWrapper(operation);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{operation.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(IOperation operation) =>
        operation is not null && LightupHelpers.CanWrapOperation(operation, WrappedType);

    public static implicit operator IInterpolatedStringContentOperationWrapper(IInterpolationOperationWrapper up) => IInterpolatedStringContentOperationWrapper.From(up.WrappedInstance);
    public static explicit operator IInterpolationOperationWrapper(IInterpolatedStringContentOperationWrapper down) => IInterpolationOperationWrapper.From(down.WrappedInstance);

}