//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class EditAndContinueMethodDebugInformationShimExtensions
{
    private static readonly Type WrappedType = typeof(EditAndContinueMethodDebugInformation);

    private static readonly Func<ImmutableArray<Byte>, ImmutableArray<Byte>, ImmutableArray<Byte>, EditAndContinueMethodDebugInformation> CreateAccessor_Overload2 = AccessorFactory.CreateStaticMethod<Func<ImmutableArray<Byte>, ImmutableArray<Byte>, ImmutableArray<Byte>, EditAndContinueMethodDebugInformation>>(WrappedType, "Create");

    extension(EditAndContinueMethodDebugInformation wrappedInstance)
    {
        public static EditAndContinueMethodDebugInformation Create(ImmutableArray<Byte> compressedSlotMap, ImmutableArray<Byte> compressedLambdaMap, ImmutableArray<Byte> compressedStateMachineStateMap) => CreateAccessor_Overload2(compressedSlotMap, compressedLambdaMap, compressedStateMachineStateMap);
    }
}