//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct IDiscardSymbolWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.IDiscardSymbol");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, bool> CanBeReferencedByNameAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "CanBeReferencedByName");
    private static readonly Func<Object, IAssemblySymbol> ContainingAssemblyAccessor = AccessorFactory.CreateProperty<Func<Object, IAssemblySymbol>>(WrappedType, "ContainingAssembly");
    private static readonly Func<Object, IModuleSymbol> ContainingModuleAccessor = AccessorFactory.CreateProperty<Func<Object, IModuleSymbol>>(WrappedType, "ContainingModule");
    private static readonly Func<Object, INamespaceSymbol> ContainingNamespaceAccessor = AccessorFactory.CreateProperty<Func<Object, INamespaceSymbol>>(WrappedType, "ContainingNamespace");
    private static readonly Func<Object, ISymbol> ContainingSymbolAccessor = AccessorFactory.CreateProperty<Func<Object, ISymbol>>(WrappedType, "ContainingSymbol");
    private static readonly Func<Object, INamedTypeSymbol> ContainingTypeAccessor = AccessorFactory.CreateProperty<Func<Object, INamedTypeSymbol>>(WrappedType, "ContainingType");
    private static readonly Func<Object, Accessibility> DeclaredAccessibilityAccessor = AccessorFactory.CreateProperty<Func<Object, Accessibility>>(WrappedType, "DeclaredAccessibility");
    private static readonly Func<Object, ImmutableArray<SyntaxReference>> DeclaringSyntaxReferencesAccessor = AccessorFactory.CreateProperty<Func<Object, ImmutableArray<SyntaxReference>>>(WrappedType, "DeclaringSyntaxReferences");
    private static readonly Func<Object, bool> HasUnsupportedMetadataAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "HasUnsupportedMetadata");
    private static readonly Func<Object, bool> IsAbstractAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsAbstract");
    private static readonly Func<Object, bool> IsDefinitionAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsDefinition");
    private static readonly Func<Object, bool> IsExternAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsExtern");
    private static readonly Func<Object, bool> IsImplicitlyDeclaredAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsImplicitlyDeclared");
    private static readonly Func<Object, bool> IsOverrideAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsOverride");
    private static readonly Func<Object, bool> IsSealedAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsSealed");
    private static readonly Func<Object, bool> IsStaticAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsStatic");
    private static readonly Func<Object, bool> IsVirtualAccessor = AccessorFactory.CreateProperty<Func<Object, bool>>(WrappedType, "IsVirtual");
    private static readonly Func<Object, SymbolKind> KindAccessor = AccessorFactory.CreateProperty<Func<Object, SymbolKind>>(WrappedType, "Kind");
    private static readonly Func<Object, string> LanguageAccessor = AccessorFactory.CreateProperty<Func<Object, string>>(WrappedType, "Language");
    private static readonly Func<Object, ImmutableArray<Location>> LocationsAccessor = AccessorFactory.CreateProperty<Func<Object, ImmutableArray<Location>>>(WrappedType, "Locations");
    private static readonly Func<Object, string> MetadataNameAccessor = AccessorFactory.CreateProperty<Func<Object, string>>(WrappedType, "MetadataName");
    private static readonly Func<Object, int> MetadataTokenAccessor = AccessorFactory.CreateProperty<Func<Object, int>>(WrappedType, "MetadataToken");
    private static readonly Func<Object, string> NameAccessor = AccessorFactory.CreateProperty<Func<Object, string>>(WrappedType, "Name");
    private static readonly Func<Object, NullableAnnotation> NullableAnnotationAccessor = AccessorFactory.CreateProperty<Func<Object, NullableAnnotation>>(WrappedType, "NullableAnnotation");
    private static readonly Func<Object, ISymbol> OriginalDefinitionAccessor = AccessorFactory.CreateProperty<Func<Object, ISymbol>>(WrappedType, "OriginalDefinition");
    private static readonly Func<Object, ITypeSymbol> TypeAccessor = AccessorFactory.CreateProperty<Func<Object, ITypeSymbol>>(WrappedType, "Type");

    private static readonly Action<Object, SymbolVisitor> AcceptAccessor = AccessorFactory.CreateMethod<Action<Object, SymbolVisitor>>(WrappedType, "Accept");
    private static readonly Func<Object, ImmutableArray<AttributeData>> GetAttributesAccessor = AccessorFactory.CreateMethod<Func<Object, ImmutableArray<AttributeData>>>(WrappedType, "GetAttributes");
    private static readonly Func<Object, string> GetDocumentationCommentIdAccessor = AccessorFactory.CreateMethod<Func<Object, string>>(WrappedType, "GetDocumentationCommentId");
    private static readonly Func<Object, CultureInfo, bool, CancellationToken, string> GetDocumentationCommentXmlAccessor = AccessorFactory.CreateMethod<Func<Object, CultureInfo, bool, CancellationToken, string>>(WrappedType, "GetDocumentationCommentXml");
    private static readonly Func<Object, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>> ToDisplayPartsAccessor = AccessorFactory.CreateMethod<Func<Object, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>>>(WrappedType, "ToDisplayParts");
    private static readonly Func<Object, SymbolDisplayFormat, string> ToDisplayStringAccessor = AccessorFactory.CreateMethod<Func<Object, SymbolDisplayFormat, string>>(WrappedType, "ToDisplayString");
    private static readonly Func<Object, SemanticModel, int, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>> ToMinimalDisplayPartsAccessor = AccessorFactory.CreateMethod<Func<Object, SemanticModel, int, SymbolDisplayFormat, ImmutableArray<SymbolDisplayPart>>>(WrappedType, "ToMinimalDisplayParts");
    private static readonly Func<Object, SemanticModel, int, SymbolDisplayFormat, string> ToMinimalDisplayStringAccessor = AccessorFactory.CreateMethod<Func<Object, SemanticModel, int, SymbolDisplayFormat, string>>(WrappedType, "ToMinimalDisplayString");

    private IDiscardSymbolWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    public bool CanBeReferencedByName => (bool)CanBeReferencedByNameAccessor(wrappedInstance);
    public IAssemblySymbol ContainingAssembly => ContainingAssemblyAccessor(wrappedInstance);
    public IModuleSymbol ContainingModule => ContainingModuleAccessor(wrappedInstance);
    public INamespaceSymbol ContainingNamespace => ContainingNamespaceAccessor(wrappedInstance);
    public ISymbol ContainingSymbol => ContainingSymbolAccessor(wrappedInstance);
    public INamedTypeSymbol ContainingType => ContainingTypeAccessor(wrappedInstance);
    public Accessibility DeclaredAccessibility => (Accessibility)DeclaredAccessibilityAccessor(wrappedInstance);
    public ImmutableArray<SyntaxReference> DeclaringSyntaxReferences => (ImmutableArray<SyntaxReference>)DeclaringSyntaxReferencesAccessor(wrappedInstance);
    public bool HasUnsupportedMetadata => (bool)HasUnsupportedMetadataAccessor(wrappedInstance);
    public bool IsAbstract => (bool)IsAbstractAccessor(wrappedInstance);
    public bool IsDefinition => (bool)IsDefinitionAccessor(wrappedInstance);
    public bool IsExtern => (bool)IsExternAccessor(wrappedInstance);
    public bool IsImplicitlyDeclared => (bool)IsImplicitlyDeclaredAccessor(wrappedInstance);
    public bool IsOverride => (bool)IsOverrideAccessor(wrappedInstance);
    public bool IsSealed => (bool)IsSealedAccessor(wrappedInstance);
    public bool IsStatic => (bool)IsStaticAccessor(wrappedInstance);
    public bool IsVirtual => (bool)IsVirtualAccessor(wrappedInstance);
    public SymbolKind Kind => (SymbolKind)KindAccessor(wrappedInstance);
    public string Language => (string)LanguageAccessor(wrappedInstance);
    public ImmutableArray<Location> Locations => (ImmutableArray<Location>)LocationsAccessor(wrappedInstance);
    public string MetadataName => (string)MetadataNameAccessor(wrappedInstance);
    public int MetadataToken => (int)MetadataTokenAccessor(wrappedInstance);
    public string Name => (string)NameAccessor(wrappedInstance);
    public NullableAnnotation NullableAnnotation => (NullableAnnotation)NullableAnnotationAccessor(wrappedInstance);
    public ISymbol OriginalDefinition => OriginalDefinitionAccessor(wrappedInstance);
    public ITypeSymbol Type => TypeAccessor(wrappedInstance);

    public void Accept(SymbolVisitor visitor) => AcceptAccessor(wrappedInstance, visitor);
    public ImmutableArray<AttributeData> GetAttributes() => (ImmutableArray<AttributeData>)GetAttributesAccessor(wrappedInstance);
    public string GetDocumentationCommentId() => (string)GetDocumentationCommentIdAccessor(wrappedInstance);
    public string GetDocumentationCommentXml(CultureInfo preferredCulture, bool expandIncludes, CancellationToken cancellationToken) => (string)GetDocumentationCommentXmlAccessor(wrappedInstance, preferredCulture, expandIncludes, cancellationToken);
    public ImmutableArray<SymbolDisplayPart> ToDisplayParts(SymbolDisplayFormat format) => (ImmutableArray<SymbolDisplayPart>)ToDisplayPartsAccessor(wrappedInstance, format);
    public string ToDisplayString(SymbolDisplayFormat format) => (string)ToDisplayStringAccessor(wrappedInstance, format);
    public ImmutableArray<SymbolDisplayPart> ToMinimalDisplayParts(SemanticModel semanticModel, int position, SymbolDisplayFormat format) => (ImmutableArray<SymbolDisplayPart>)ToMinimalDisplayPartsAccessor(wrappedInstance, semanticModel, position, format);
    public string ToMinimalDisplayString(SemanticModel semanticModel, int position, SymbolDisplayFormat format) => (string)ToMinimalDisplayStringAccessor(wrappedInstance, semanticModel, position, format);

    public static IDiscardSymbolWrapper From(object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new IDiscardSymbolWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.IDiscardSymbol'");
        }
    }

    public static bool IsInstance(object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}