//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class CSharpCommandLineArgumentsShimExtensions
{
    private static readonly Type WrappedType = typeof(CSharpCommandLineArguments);

    private static readonly Func<CSharpCommandLineArguments, ImmutableArray<string>> AnalyzerConfigPathsAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, ImmutableArray<string>>>(WrappedType, "AnalyzerConfigPaths");
    private static readonly Func<CSharpCommandLineArguments, bool> DisplayLangVersionsAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, bool>>(WrappedType, "DisplayLangVersions");
    private static readonly Func<CSharpCommandLineArguments, bool> DisplayVersionAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, bool>>(WrappedType, "DisplayVersion");
    private static readonly Func<CSharpCommandLineArguments, ImmutableArray<CommandLineSourceFile>> EmbeddedFilesAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, ImmutableArray<CommandLineSourceFile>>>(WrappedType, "EmbeddedFiles");
    private static readonly Func<CSharpCommandLineArguments, bool> EmitPdbFileAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, bool>>(WrappedType, "EmitPdbFile");
    private static readonly Func<CSharpCommandLineArguments, ErrorLogOptionsWrapper> ErrorLogOptionsAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, ErrorLogOptionsWrapper>>(WrappedType, "ErrorLogOptions");
    private static readonly Func<CSharpCommandLineArguments, string> GeneratedFilesOutputDirectoryAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, string>>(WrappedType, "GeneratedFilesOutputDirectory");
    private static readonly Func<CSharpCommandLineArguments, ImmutableArray<CommandLineResourceWrapper>> ManifestResourceArgumentsAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, ImmutableArray<CommandLineResourceWrapper>>>(WrappedType, "ManifestResourceArguments");
    private static readonly Func<CSharpCommandLineArguments, string> OutputRefFilePathAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, string>>(WrappedType, "OutputRefFilePath");
    private static readonly Func<CSharpCommandLineArguments, bool> ReportInternalsVisibleToAttributesAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, bool>>(WrappedType, "ReportInternalsVisibleToAttributes");
    private static readonly Func<CSharpCommandLineArguments, string> RuleSetPathAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, string>>(WrappedType, "RuleSetPath");
    private static readonly Func<CSharpCommandLineArguments, bool> SkipAnalyzersAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, bool>>(WrappedType, "SkipAnalyzers");
    private static readonly Func<CSharpCommandLineArguments, string> SourceLinkAccessor = AccessorFactory.CreateProperty<Func<CSharpCommandLineArguments, string>>(WrappedType, "SourceLink");

    private static readonly Func<CSharpCommandLineArguments, string, string> GetOutputFilePathAccessor = AccessorFactory.CreateMethod<Func<CSharpCommandLineArguments, string, string>>(WrappedType, "GetOutputFilePath");
    private static readonly Func<CSharpCommandLineArguments, string, string> GetPdbFilePathAccessor = AccessorFactory.CreateMethod<Func<CSharpCommandLineArguments, string, string>>(WrappedType, "GetPdbFilePath");

    extension(CSharpCommandLineArguments wrappedInstance)
    {
        public ImmutableArray<string> AnalyzerConfigPaths => AnalyzerConfigPathsAccessor(wrappedInstance);
        public bool DisplayLangVersions => DisplayLangVersionsAccessor(wrappedInstance);
        public bool DisplayVersion => DisplayVersionAccessor(wrappedInstance);
        public ImmutableArray<CommandLineSourceFile> EmbeddedFiles => EmbeddedFilesAccessor(wrappedInstance);
        public bool EmitPdbFile => EmitPdbFileAccessor(wrappedInstance);
        public ErrorLogOptionsWrapper ErrorLogOptions => ErrorLogOptionsAccessor(wrappedInstance);
        public string GeneratedFilesOutputDirectory => GeneratedFilesOutputDirectoryAccessor(wrappedInstance);
        public ImmutableArray<CommandLineResourceWrapper> ManifestResourceArguments => ManifestResourceArgumentsAccessor(wrappedInstance);
        public string OutputRefFilePath => OutputRefFilePathAccessor(wrappedInstance);
        public bool ReportInternalsVisibleToAttributes => ReportInternalsVisibleToAttributesAccessor(wrappedInstance);
        public string RuleSetPath => RuleSetPathAccessor(wrappedInstance);
        public bool SkipAnalyzers => SkipAnalyzersAccessor(wrappedInstance);
        public string SourceLink => SourceLinkAccessor(wrappedInstance);

        public string GetOutputFilePath(string outputFileName) => GetOutputFilePathAccessor(wrappedInstance, outputFileName);
        public string GetPdbFilePath(string outputFileName) => GetPdbFilePathAccessor(wrappedInstance, outputFileName);
    }
}