//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) 2014-2025 SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct FunctionPointerParameterSyntaxWrapper: ISyntaxWrapper<CSharpSyntaxNode>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.FunctionPointerParameterSyntax";
    private static readonly Type WrappedType;

    private readonly CSharpSyntaxNode node;

    static FunctionPointerParameterSyntaxWrapper()
    {
        WrappedType = SyntaxNodeTypes.LatestType(typeof(FunctionPointerParameterSyntaxWrapper));
        AttributeListsAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<CSharpSyntaxNode, SyntaxList<AttributeListSyntax>>(WrappedType, "AttributeLists");
        ModifiersAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<CSharpSyntaxNode, SyntaxTokenList>(WrappedType, "Modifiers");
        TypeAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<CSharpSyntaxNode, TypeSyntax>(WrappedType, "Type");
    }

    private FunctionPointerParameterSyntaxWrapper(CSharpSyntaxNode node) =>
        this.node = node;

    public CSharpSyntaxNode Node => this.node;

    [Obsolete("Use Node instead")]
    public CSharpSyntaxNode SyntaxNode => this.node;

    private static readonly Func<CSharpSyntaxNode, SyntaxList<AttributeListSyntax>> AttributeListsAccessor;
    public SyntaxList<AttributeListSyntax> AttributeLists => (SyntaxList<AttributeListSyntax>)AttributeListsAccessor(this.node);
    private static readonly Func<CSharpSyntaxNode, SyntaxTokenList> ModifiersAccessor;
    public SyntaxTokenList Modifiers => (SyntaxTokenList)ModifiersAccessor(this.node);
    private static readonly Func<CSharpSyntaxNode, TypeSyntax> TypeAccessor;
    public TypeSyntax Type => TypeAccessor(this.node);
    public String Language => this.node.Language;
    public Int32 RawKind => this.node.RawKind;
    public TextSpan FullSpan => this.node.FullSpan;
    public TextSpan Span => this.node.Span;
    public Int32 SpanStart => this.node.SpanStart;
    public Boolean IsMissing => this.node.IsMissing;
    public Boolean IsStructuredTrivia => this.node.IsStructuredTrivia;
    public Boolean HasStructuredTrivia => this.node.HasStructuredTrivia;
    public Boolean ContainsSkippedText => this.node.ContainsSkippedText;
    public Boolean ContainsDiagnostics => this.node.ContainsDiagnostics;
    public Boolean ContainsDirectives => this.node.ContainsDirectives;
    public Boolean HasLeadingTrivia => this.node.HasLeadingTrivia;
    public Boolean HasTrailingTrivia => this.node.HasTrailingTrivia;
    public SyntaxNode Parent => this.node.Parent;
    public SyntaxTrivia ParentTrivia => this.node.ParentTrivia;
    public Boolean ContainsAnnotations => this.node.ContainsAnnotations;

    public static explicit operator FunctionPointerParameterSyntaxWrapper(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }

        if (!IsInstance(node))
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }

        return new FunctionPointerParameterSyntaxWrapper((CSharpSyntaxNode)node);
    }

    public static implicit operator CSharpSyntaxNode(FunctionPointerParameterSyntaxWrapper wrapper) =>
        wrapper.node;

    public static implicit operator BaseParameterSyntaxWrapper(FunctionPointerParameterSyntaxWrapper up) => (BaseParameterSyntaxWrapper)up.SyntaxNode;
    public static explicit operator FunctionPointerParameterSyntaxWrapper(BaseParameterSyntaxWrapper down) => (FunctionPointerParameterSyntaxWrapper)down.SyntaxNode;

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);
}