//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct MethodInstrumentationWrapper : IWrapper, IEquatable<MethodInstrumentationWrapper>
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.Emit.MethodInstrumentation");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, ImmutableArray<InstrumentationKind>> KindsAccessor = AccessorFactory.CreateProperty<Func<Object, ImmutableArray<InstrumentationKind>>>(WrappedType, "Kinds");

    private MethodInstrumentationWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    object IWrapper.WrappedInstance => wrappedInstance;

    public override int GetHashCode() =>
        wrappedInstance?.GetHashCode() ?? 0;

    public override bool Equals(object obj) =>
        (obj is IWrapper wrapper && Equals(wrappedInstance, wrapper.WrappedInstance))
        || Equals(wrappedInstance, obj);

    public bool Equals(MethodInstrumentationWrapper other) =>
        Equals(wrappedInstance, other.wrappedInstance);

    public static bool operator ==(MethodInstrumentationWrapper left, MethodInstrumentationWrapper right) =>
        Equals(left.wrappedInstance, right.wrappedInstance);

    public static bool operator !=(MethodInstrumentationWrapper left, MethodInstrumentationWrapper right) =>
        !Equals(left.wrappedInstance, right.wrappedInstance);

    public ImmutableArray<InstrumentationKind> Kinds => KindsAccessor(wrappedInstance);

    public static MethodInstrumentationWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new MethodInstrumentationWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.Emit.MethodInstrumentation'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}