//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct ImplicitObjectCreationExpressionSyntaxWrapper : ISyntaxWrapper<ExpressionSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.ImplicitObjectCreationExpressionSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(ImplicitObjectCreationExpressionSyntaxWrapper));
    private readonly ExpressionSyntax wrappedInstance;

    private static readonly Func<ExpressionSyntax, ArgumentListSyntax> ArgumentListAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, ArgumentListSyntax>>(WrappedType, "ArgumentList");
    private static readonly Func<ExpressionSyntax, InitializerExpressionSyntax> InitializerAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, InitializerExpressionSyntax>>(WrappedType, "Initializer");
    private static readonly Func<ExpressionSyntax, SyntaxToken> NewKeywordAccessor = AccessorFactory.CreateProperty<Func<ExpressionSyntax, SyntaxToken>>(WrappedType, "NewKeyword");

    private ImplicitObjectCreationExpressionSyntaxWrapper(ExpressionSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public ExpressionSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public ExpressionSyntax SyntaxNode => wrappedInstance;

    public ExpressionSyntax WrappedInstance => wrappedInstance;

    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public String Language => wrappedInstance.Language;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;

    public ArgumentListSyntax ArgumentList => ArgumentListAccessor(wrappedInstance);
    public InitializerExpressionSyntax Initializer => InitializerAccessor(wrappedInstance);
    public SyntaxToken NewKeyword => (SyntaxToken)NewKeywordAccessor(wrappedInstance);

    public static explicit operator ImplicitObjectCreationExpressionSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator ExpressionSyntax(ImplicitObjectCreationExpressionSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static ImplicitObjectCreationExpressionSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new ImplicitObjectCreationExpressionSyntaxWrapper((ExpressionSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

    public static implicit operator BaseObjectCreationExpressionSyntaxWrapper(ImplicitObjectCreationExpressionSyntaxWrapper up) => BaseObjectCreationExpressionSyntaxWrapper.From(up.WrappedInstance);
    public static explicit operator ImplicitObjectCreationExpressionSyntaxWrapper(BaseObjectCreationExpressionSyntaxWrapper down) => ImplicitObjectCreationExpressionSyntaxWrapper.From(down.WrappedInstance);

}