//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class SymbolAnalysisContextShimExtensions
{
    private static readonly Type WrappedType = typeof(SymbolAnalysisContext);

    private static readonly Func<SymbolAnalysisContext, Nullable<TextSpan>> FilterSpanAccessor = AccessorFactory.CreateProperty<Func<SymbolAnalysisContext, Nullable<TextSpan>>>(WrappedType, "FilterSpan");
    private static readonly Func<SymbolAnalysisContext, SyntaxTree> FilterTreeAccessor = AccessorFactory.CreateProperty<Func<SymbolAnalysisContext, SyntaxTree>>(WrappedType, "FilterTree");
    private static readonly Func<SymbolAnalysisContext, bool> IsGeneratedCodeAccessor = AccessorFactory.CreateProperty<Func<SymbolAnalysisContext, bool>>(WrappedType, "IsGeneratedCode");

    extension(SymbolAnalysisContext wrappedInstance)
    {
        public Nullable<TextSpan> FilterSpan => FilterSpanAccessor(wrappedInstance);
        public SyntaxTree FilterTree => FilterTreeAccessor(wrappedInstance);
        public bool IsGeneratedCode => IsGeneratedCodeAccessor(wrappedInstance);
    }
}