//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public readonly struct AnalyzerConfigOptionsProviderWrapper
{
    private static readonly Type WrappedType = TypeRegister.LatestType("Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider");
    private static readonly ConcurrentDictionary<Type, bool> CanWrapCache = new();
    private readonly Object wrappedInstance;

    private static readonly Func<Object, Object> GlobalOptionsAccessor = AccessorFactory.CreateProperty<Func<Object, Object>>(WrappedType, "GlobalOptions");

    private static readonly Func<Object, AdditionalText, Object> GetOptionsAccessor = AccessorFactory.CreateMethod<Func<Object, AdditionalText, Object>>(WrappedType, "GetOptions");
    private static readonly Func<Object, SyntaxTree, Object> GetOptionsAccessor_Overload2 = AccessorFactory.CreateMethod<Func<Object, SyntaxTree, Object>>(WrappedType, "GetOptions");

    private AnalyzerConfigOptionsProviderWrapper(Object wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    public Object WrappedInstance => wrappedInstance;

    public AnalyzerConfigOptionsWrapper GlobalOptions => AnalyzerConfigOptionsWrapper.From(GlobalOptionsAccessor(wrappedInstance));

    public AnalyzerConfigOptionsWrapper GetOptions(AdditionalText textFile) => AnalyzerConfigOptionsWrapper.From(GetOptionsAccessor(wrappedInstance, textFile));
    public AnalyzerConfigOptionsWrapper GetOptions(SyntaxTree tree) => AnalyzerConfigOptionsWrapper.From(GetOptionsAccessor_Overload2(wrappedInstance, tree));

    public static AnalyzerConfigOptionsProviderWrapper From(Object instance)
    {
        if (instance is null)
        {
            return default;
        }
        else if (IsInstance(instance))
        {
            return new AnalyzerConfigOptionsProviderWrapper((Object)instance);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{instance.GetType().FullName}' to 'Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider'");
        }
    }

    public static bool IsInstance(Object instance) =>
        WrappedType.CanWrap(CanWrapCache, instance);
}