//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct ISwitchCaseOperationWrapper : IOperationWrapper
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.ISwitchCaseOperation";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(ISwitchCaseOperationWrapper));
    private readonly IOperation wrappedInstance;

    private ISwitchCaseOperationWrapper(IOperation wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public IOperation WrappedOperation => wrappedInstance;

    public IOperation WrappedInstance => wrappedInstance;

    private static readonly Func<IOperation, ImmutableArray<IOperation>> ClausesAccessor = LightupHelpers.CreateOperationListPropertyAccessor<IOperation>(WrappedType, nameof(Clauses));
    public ImmutableArray<IOperation> Clauses => ClausesAccessor(wrappedInstance);
    private static readonly Func<IOperation, ImmutableArray<IOperation>> BodyAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, ImmutableArray<IOperation>>(WrappedType, "Body");
    public ImmutableArray<IOperation> Body => (ImmutableArray<IOperation>)BodyAccessor(wrappedInstance);
    private static readonly Func<IOperation, ImmutableArray<ILocalSymbol>> LocalsAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, ImmutableArray<ILocalSymbol>>(WrappedType, "Locals");
    public ImmutableArray<ILocalSymbol> Locals => (ImmutableArray<ILocalSymbol>)LocalsAccessor(wrappedInstance);
    private static readonly Func<IOperation, IOperation> ParentAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, IOperation>(WrappedType, "Parent");
    public IOperation Parent => ParentAccessor(wrappedInstance);
    public OperationKind Kind => wrappedInstance.Kind;
    public SyntaxNode Syntax => wrappedInstance.Syntax;
    public ITypeSymbol Type => wrappedInstance.Type;
    public Optional<Object> ConstantValue => wrappedInstance.ConstantValue;
    private static readonly Func<IOperation, IEnumerable<IOperation>> ChildrenAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, IEnumerable<IOperation>>(WrappedType, "Children");
    [System.ObsoleteAttribute("This API has performance penalties, please use ChildOperations instead.", false)]
    public IEnumerable<IOperation> Children => (IEnumerable<IOperation>)ChildrenAccessor(wrappedInstance);
    private static readonly Func<IOperation, String> LanguageAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, String>(WrappedType, "Language");
    public String Language => (String)LanguageAccessor(wrappedInstance);
    private static readonly Func<IOperation, Boolean> IsImplicitAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, Boolean>(WrappedType, "IsImplicit");
    public Boolean IsImplicit => (Boolean)IsImplicitAccessor(wrappedInstance);
    private static readonly Func<IOperation, SemanticModel> SemanticModelAccessor = LightupHelpers.CreatePropertyAccessor<IOperation, SemanticModel>(WrappedType, "SemanticModel");
    public SemanticModel SemanticModel => (SemanticModel)SemanticModelAccessor(wrappedInstance);

    [Obsolete("Use From instead")]
    public static ISwitchCaseOperationWrapper FromOperation(IOperation operation) =>
        From(operation);

    public static ISwitchCaseOperationWrapper From(IOperation operation)
    {
        if (operation is null)
        {
            return default;
        }
        else if (IsInstance(operation))
        {
            return new ISwitchCaseOperationWrapper(operation);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{operation.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(IOperation operation) =>
        operation is not null && LightupHelpers.CanWrapOperation(operation, WrappedType);

}