//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public readonly partial struct TupleTypeSyntaxWrapper : ISyntaxWrapper<TypeSyntax>
{
    public const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.TupleTypeSyntax";

    private static readonly Type WrappedType = TypeRegister.LatestType(typeof(TupleTypeSyntaxWrapper));
    private readonly TypeSyntax wrappedInstance;

    private static readonly Func<TypeSyntax, SyntaxToken> CloseParenTokenAccessor = AccessorFactory.CreateProperty<Func<TypeSyntax, SyntaxToken>>(WrappedType, "CloseParenToken");
    private static readonly Func<TypeSyntax, SeparatedSyntaxListWrapper<TupleElementSyntaxWrapper>> ElementsAccessor = LightupHelpers.CreateSeparatedSyntaxListPropertyAccessor<TypeSyntax, TupleElementSyntaxWrapper>(WrappedType, nameof(Elements));
    private static readonly Func<TypeSyntax, Boolean> IsNintAccessor = AccessorFactory.CreateProperty<Func<TypeSyntax, Boolean>>(WrappedType, "IsNint");
    private static readonly Func<TypeSyntax, Boolean> IsNotNullAccessor = AccessorFactory.CreateProperty<Func<TypeSyntax, Boolean>>(WrappedType, "IsNotNull");
    private static readonly Func<TypeSyntax, Boolean> IsNuintAccessor = AccessorFactory.CreateProperty<Func<TypeSyntax, Boolean>>(WrappedType, "IsNuint");
    private static readonly Func<TypeSyntax, Boolean> IsUnmanagedAccessor = AccessorFactory.CreateProperty<Func<TypeSyntax, Boolean>>(WrappedType, "IsUnmanaged");
    private static readonly Func<TypeSyntax, SyntaxToken> OpenParenTokenAccessor = AccessorFactory.CreateProperty<Func<TypeSyntax, SyntaxToken>>(WrappedType, "OpenParenToken");

    private TupleTypeSyntaxWrapper(TypeSyntax wrappedInstance) =>
        this.wrappedInstance = wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public TypeSyntax Node => wrappedInstance;

    [Obsolete("Use WrappedInstance instead")]
    public TypeSyntax SyntaxNode => wrappedInstance;

    public TypeSyntax WrappedInstance => wrappedInstance;

    public Boolean ContainsAnnotations => wrappedInstance.ContainsAnnotations;
    public Boolean ContainsDiagnostics => wrappedInstance.ContainsDiagnostics;
    public Boolean ContainsDirectives => wrappedInstance.ContainsDirectives;
    public Boolean ContainsSkippedText => wrappedInstance.ContainsSkippedText;
    public TextSpan FullSpan => wrappedInstance.FullSpan;
    public Boolean HasLeadingTrivia => wrappedInstance.HasLeadingTrivia;
    public Boolean HasStructuredTrivia => wrappedInstance.HasStructuredTrivia;
    public Boolean HasTrailingTrivia => wrappedInstance.HasTrailingTrivia;
    public Boolean IsMissing => wrappedInstance.IsMissing;
    public Boolean IsStructuredTrivia => wrappedInstance.IsStructuredTrivia;
    public Boolean IsVar => wrappedInstance.IsVar;
    public String Language => wrappedInstance.Language;
    public SyntaxNode Parent => wrappedInstance.Parent;
    public SyntaxTrivia ParentTrivia => wrappedInstance.ParentTrivia;
    public Int32 RawKind => wrappedInstance.RawKind;
    public TextSpan Span => wrappedInstance.Span;
    public Int32 SpanStart => wrappedInstance.SpanStart;

    public SyntaxToken CloseParenToken => (SyntaxToken)CloseParenTokenAccessor(wrappedInstance);
    public SeparatedSyntaxListWrapper<TupleElementSyntaxWrapper> Elements => ElementsAccessor(wrappedInstance);
    public Boolean IsNint => (Boolean)IsNintAccessor(wrappedInstance);
    public Boolean IsNotNull => (Boolean)IsNotNullAccessor(wrappedInstance);
    public Boolean IsNuint => (Boolean)IsNuintAccessor(wrappedInstance);
    public Boolean IsUnmanaged => (Boolean)IsUnmanagedAccessor(wrappedInstance);
    public SyntaxToken OpenParenToken => (SyntaxToken)OpenParenTokenAccessor(wrappedInstance);

    public static explicit operator TupleTypeSyntaxWrapper(SyntaxNode node) =>
        From(node);

    public static implicit operator TypeSyntax(TupleTypeSyntaxWrapper wrapper) =>
        wrapper.wrappedInstance;

    public static TupleTypeSyntaxWrapper From(SyntaxNode node)
    {
        if (node is null)
        {
            return default;
        }
        else if (IsInstance(node))
        {
            return new TupleTypeSyntaxWrapper((TypeSyntax)node);
        }
        else
        {
            throw new InvalidCastException($"Cannot cast '{node.GetType().FullName}' to '{WrappedTypeName}'");
        }
    }

    public static bool IsInstance(SyntaxNode node) =>
        node is not null && LightupHelpers.CanWrapNode(node, WrappedType);

}