//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

namespace SonarAnalyzer.ShimLayer;

public static class ISourceAssemblySymbolShimExtensions
{
    private static readonly Type WrappedType = typeof(ISourceAssemblySymbol);

    private static readonly Func<ISourceAssemblySymbol, int> MetadataTokenAccessor = AccessorFactory.CreateProperty<Func<ISourceAssemblySymbol, int>>(WrappedType, "MetadataToken");

    private static readonly Func<ISourceAssemblySymbol, ImmutableArray<INamedTypeSymbol>> GetForwardedTypesAccessor = AccessorFactory.CreateMethod<Func<ISourceAssemblySymbol, ImmutableArray<INamedTypeSymbol>>>(WrappedType, "GetForwardedTypes");

    extension(ISourceAssemblySymbol wrappedInstance)
    {
        public int MetadataToken => MetadataTokenAccessor(wrappedInstance);

        public ImmutableArray<INamedTypeSymbol> GetForwardedTypes() => GetForwardedTypesAccessor(wrappedInstance);
    }
}