//<auto-generated/>
/*
 * SonarAnalyzer for .NET
 * Copyright (C) 2014-2025 SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace SonarAnalyzer.ShimLayer;

public static partial class IdentifierNameSyntaxShimExtensions
{
    private static readonly Type WrappedType = typeof(IdentifierNameSyntax);

    private static readonly Func<IdentifierNameSyntax, Boolean> IsUnmanagedAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<IdentifierNameSyntax, Boolean>(WrappedType, "IsUnmanaged");

    private static readonly Func<IdentifierNameSyntax, Boolean> IsNotNullAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<IdentifierNameSyntax, Boolean>(WrappedType, "IsNotNull");

    private static readonly Func<IdentifierNameSyntax, Boolean> IsNintAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<IdentifierNameSyntax, Boolean>(WrappedType, "IsNint");

    private static readonly Func<IdentifierNameSyntax, Boolean> IsNuintAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<IdentifierNameSyntax, Boolean>(WrappedType, "IsNuint");

    extension(IdentifierNameSyntax @this)
    {
        public Boolean IsUnmanaged => (Boolean)IsUnmanagedAccessor(@this);
        public Boolean IsNotNull => (Boolean)IsNotNullAccessor(@this);
        public Boolean IsNint => (Boolean)IsNintAccessor(@this);
        public Boolean IsNuint => (Boolean)IsNuintAccessor(@this);
    }
}