/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis.CSharp.Syntax;
using SonarAnalyzer.TestFramework.Extensions;

namespace SonarAnalyzer.ShimLayer.Generator.Strategies.Test;

[TestClass]
public class ExtendStrategyTest
{
    [TestMethod]
    public void Generate_TypeDeclarationSyntax_Empty()
    {
        var sut = new ExtendStrategy(typeof(TypeDeclarationSyntax), []);
        sut.Generate([]).Should().BeNull();
    }

    [TestMethod]
    public void Generate_ClassDeclarationSyntax_ParameterList()
    {
        var sut = new ExtendStrategy(typeof(ClassDeclarationSyntax), [
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntax.ParameterList))[0], false, "ParameterListAccessor"),
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntax.SemicolonToken))[0], false, "SemicolonTokenAccessor"),
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntax.Span))[0], true, "SpanAccessor"),                                        // Exisiting member => ignored
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntaxShimExtensions.AddParameterListParameters))[0], false, "AddParameterListParametersAccessor"),
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntax.FirstAncestorOrSelf))[0], false, "FirstAncestorOrSelfAccessor"),         // Generic => ignored
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntax.IsIncrementallyIdenticalTo))[0], false, "IsIncrementallyIdenticalTo"),   // Unsupported parameter => ignored
        ]);
        var model = new Dictionary<Type, Strategy>
        {
            { typeof(bool), new SkipStrategy(typeof(bool)) }    // Fake scaffolding to prove that unsupported parameter is ignored
        };
        var result = sut.Generate(new(model));
        result.Should().BeIgnoringLineEndings(
            """
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             *
             * You can redistribute and/or modify this program under the terms of
             * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */

            using Microsoft.CodeAnalysis.CSharp.Syntax;

            namespace SonarAnalyzer.ShimLayer;

            public static partial class ClassDeclarationSyntaxShimExtensions
            {
                private static readonly Type WrappedType = typeof(ClassDeclarationSyntax);

                private static readonly Func<ClassDeclarationSyntax, ParameterListSyntax> ParameterListAccessor = AccessorFactory.CreateProperty<Func<ClassDeclarationSyntax, ParameterListSyntax>>(WrappedType, "ParameterList");
                private static readonly Func<ClassDeclarationSyntax, SyntaxToken> SemicolonTokenAccessor = AccessorFactory.CreateProperty<Func<ClassDeclarationSyntax, SyntaxToken>>(WrappedType, "SemicolonToken");

                private static readonly Func<ClassDeclarationSyntax, ParameterSyntax[], ClassDeclarationSyntax> AddParameterListParametersAccessor = AccessorFactory.CreateMethod<Func<ClassDeclarationSyntax, ParameterSyntax[], ClassDeclarationSyntax>>(WrappedType, "AddParameterListParameters");

                extension(ClassDeclarationSyntax wrappedInstance)
                {
                    public ParameterListSyntax ParameterList => (ParameterListSyntax)ParameterListAccessor(wrappedInstance);
                    public SyntaxToken SemicolonToken => (SyntaxToken)SemicolonTokenAccessor(wrappedInstance);

                    public ClassDeclarationSyntax AddParameterListParameters(ParameterSyntax[] items) => (ClassDeclarationSyntax)AddParameterListParametersAccessor(wrappedInstance, items);
                }
            }
            """);
    }

    [TestMethod]
    public void Generate_OnlyMethods_NoProperties()
    {
        var sut = new ExtendStrategy(typeof(ClassDeclarationSyntax), [
            new(typeof(ClassDeclarationSyntax).GetMember(nameof(ClassDeclarationSyntaxShimExtensions.AddParameterListParameters))[0], false, "AddParameterListParametersAccessor"),
        ]);
        var result = sut.Generate([]);
        result.Should().BeIgnoringLineEndings(
            """
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             *
             * You can redistribute and/or modify this program under the terms of
             * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */

            using Microsoft.CodeAnalysis.CSharp.Syntax;

            namespace SonarAnalyzer.ShimLayer;

            public static partial class ClassDeclarationSyntaxShimExtensions
            {
                private static readonly Type WrappedType = typeof(ClassDeclarationSyntax);

                private static readonly Func<ClassDeclarationSyntax, ParameterSyntax[], ClassDeclarationSyntax> AddParameterListParametersAccessor = AccessorFactory.CreateMethod<Func<ClassDeclarationSyntax, ParameterSyntax[], ClassDeclarationSyntax>>(WrappedType, "AddParameterListParameters");

                extension(ClassDeclarationSyntax wrappedInstance)
                {
                    public ClassDeclarationSyntax AddParameterListParameters(ParameterSyntax[] items) => (ClassDeclarationSyntax)AddParameterListParametersAccessor(wrappedInstance, items);
                }
            }
            """);
    }

    [TestMethod]
    public void Generate_ProcessStartInfo_GetterOnly()
    {
        var sut = new ExtendStrategy(typeof(ProcessStartInfo), [
            // FileName has a getter and a setter. We do not generate setters, because there are no SyntaxNode properties with setters.
            new(typeof(ProcessStartInfo).GetMember(nameof(ProcessStartInfo.FileName))[0], false, "FileNameAccessor"),
        ]);
        var result = sut.Generate([]);
        result.Should().BeIgnoringLineEndings(
            """
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             *
             * You can redistribute and/or modify this program under the terms of
             * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */

            using System.Diagnostics;

            namespace SonarAnalyzer.ShimLayer;

            public static partial class ProcessStartInfoShimExtensions
            {
                private static readonly Type WrappedType = typeof(ProcessStartInfo);

                private static readonly Func<ProcessStartInfo, string> FileNameAccessor = AccessorFactory.CreateProperty<Func<ProcessStartInfo, string>>(WrappedType, "FileName");

                extension(ProcessStartInfo wrappedInstance)
                {
                    [System.ComponentModel.EditorAttribute("System.Diagnostics.Design.StartFileNameEditor, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "System.Drawing.Design.UITypeEditor, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
                    public string FileName => (string)FileNameAccessor(wrappedInstance);
                }
            }
            """);
    }
}
