/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis.Operations;
using SonarAnalyzer.TestFramework.Extensions;

namespace SonarAnalyzer.ShimLayer.Generator.Strategies.Test;

[TestClass]
public class IOperationStrategyTest
{
    [TestMethod]
    public void Generate_IOperation()
    {
        var sut = new IOperationStrategy(
            typeof(IOperation),
            [
                new(typeof(IOperation).GetMember(nameof(IOperation.Parent))[0], false, "ParentAccessor"),
                new(typeof(IOperation).GetMember(nameof(IOperation.Children))[0], false, "ChildrenAccessor"),
                new(typeof(IOperation).GetMember(nameof(IOperation.Syntax))[0], true, "SyntaxAccessor"),    // Existing member, should be ignored
                new(typeof(IOperation).GetMember(nameof(IOperation.Accept))[0], false, "AcceptAccessor"),   // Unsupported return type: void
            ]);
        var model = new Dictionary<Type, Strategy>
        {
            { typeof(void), new SkipStrategy(typeof(void)) },
            { typeof(IInvocationOperation), new OperationWrapStrategy(typeof(IInvocationOperation), []) },
            { typeof(IPropertyReferenceOperation), new OperationWrapStrategy(typeof(IPropertyReferenceOperation), []) }
        };
        var result = sut.Generate(new(model));
        result.Should().BeIgnoringLineEndings(
            """
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             *
             * You can redistribute and/or modify this program under the terms of
             * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */

            using Microsoft.CodeAnalysis;
            using Microsoft.CodeAnalysis.CSharp;
            using Microsoft.CodeAnalysis.CSharp.Syntax;
            using Microsoft.CodeAnalysis.Text;
            using System;
            using System.Collections.Immutable;
            using System.Text;

            namespace SonarAnalyzer.ShimLayer;

            public static partial class IOperationShimExtensions
            {
                private static readonly Type WrappedType = typeof(IOperation);

                private static readonly Func<IOperation, IOperation> ParentAccessor = AccessorFactory.CreateProperty<Func<IOperation, IOperation>>(WrappedType, "Parent");
                private static readonly Func<IOperation, IEnumerable<IOperation>> ChildrenAccessor = AccessorFactory.CreateProperty<Func<IOperation, IEnumerable<IOperation>>>(WrappedType, "Children");

                extension(IOperation wrappedInstance)
                {
                    public IOperation Parent => (IOperation)ParentAccessor(wrappedInstance);
                    [System.ObsoleteAttribute("This API has performance penalties, please use ChildOperations instead.", false)]
                    public IEnumerable<IOperation> Children => (IEnumerable<IOperation>)ChildrenAccessor(wrappedInstance);

                    public IInvocationOperationWrapper? AsInvocation => IInvocationOperationWrapper.FromOrDefault(wrappedInstance);
                    public IPropertyReferenceOperationWrapper? AsPropertyReference => IPropertyReferenceOperationWrapper.FromOrDefault(wrappedInstance);

                    public IInvocationOperationWrapper ToInvocation() => IInvocationOperationWrapper.From(wrappedInstance);
                    public IPropertyReferenceOperationWrapper ToPropertyReference() => IPropertyReferenceOperationWrapper.From(wrappedInstance);
                }
            }
            """);
    }
}
