/*
 * SonarAnalyzer for .NET
 * Copyright (C) 2014-2025 SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using System.Diagnostics.CodeAnalysis;
using SonarAnalyzer.TestFramework.Extensions;

namespace SonarAnalyzer.ShimLayer.Generator.Strategies.Test;

[TestClass]
public class NewEnumStrategyTest
{
    [Experimental("RSEXPERIMENTAL001")] // Microsoft.CodeAnalysis.SemanticModelOptions' is for evaluation purposes only and is subject to change or removal in future updates.
    private enum EnumWithExperimentalAttribute
    {
        Lorem,
        Ipsum,
    }

    [TestMethod]
    public void Generate()
    {
        using var typeLoader = new TypeLoader();
        var type = typeLoader.LoadLatest().Single(x => x.Type.Name == nameof(IncrementalGeneratorOutputKind));
        var sut = new NewEnumStrategy(type.Type, type.Members.OfType<FieldInfo>().Where(x => x.Name != "value__").ToArray());
        sut.Generate([]).Should().BeIgnoringLineEndings("""
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) 2014-2025 SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             * This program is free software; you can redistribute it and/or
             * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */
            
            using Microsoft.CodeAnalysis;
            using Microsoft.CodeAnalysis.CSharp;
            using Microsoft.CodeAnalysis.CSharp.Syntax;
            using Microsoft.CodeAnalysis.Text;
            using System;
            using System.Collections.Immutable;

            namespace SonarAnalyzer.ShimLayer;

            [System.FlagsAttribute]
            public enum IncrementalGeneratorOutputKind : System.Int32
            {
                None = 0,
                Source = 1,
                PostInit = 2,
                Implementation = 4,
                Host = 8,
            }

            """);
    }

    [TestMethod]
    public void Generate_IgnoreExperimentalAttribute()
    {
#pragma warning disable RSEXPERIMENTAL001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
        var type = typeof(EnumWithExperimentalAttribute);
        var sut = new NewEnumStrategy(type, type.GetMembers().OfType<FieldInfo>().Where(x => x.Name != "value__").ToArray());
        sut.Generate([]).Should().BeIgnoringLineEndings("""
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) 2014-2025 SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             * This program is free software; you can redistribute it and/or
             * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */
            
            using Microsoft.CodeAnalysis;
            using Microsoft.CodeAnalysis.CSharp;
            using Microsoft.CodeAnalysis.CSharp.Syntax;
            using Microsoft.CodeAnalysis.Text;
            using System;
            using System.Collections.Immutable;

            namespace SonarAnalyzer.ShimLayer;

            public enum EnumWithExperimentalAttribute : System.Int32
            {
                Lorem = 0,
                Ipsum = 1,
            }

            """);
    }
}
