/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using Microsoft.CodeAnalysis.CSharp.Syntax;
using SonarAnalyzer.TestFramework.Extensions;
using CSharpExtensions = Microsoft.CodeAnalysis.CSharp.CSharpExtensions;

namespace SonarAnalyzer.ShimLayer.Generator.Strategies.Test;

[TestClass]
public class StaticClassExtendStrategyTest
{
    [TestMethod]
    public void Generate_Members()
    {
        var tryGetSpeculativeSemanticModel = typeof(CSharpExtensions).GetMethod(
            nameof(CSharpExtensions.TryGetSpeculativeSemanticModel),
            [typeof(SemanticModel), typeof(int), typeof(PrimaryConstructorBaseTypeSyntax), typeof(SemanticModel).MakeByRefType()]);
        var sut = new StaticClassExtendStrategy(
            typeof(CSharpExtensions),
            [
                new(typeof(CSharpExtensions).GetMember(nameof(CSharpExtensions.Kind))[0], true, "KindAccessor"),                            // Passthrough => ignored
                new(typeof(CSharpExtensions).GetMember(nameof(CSharpExtensions.GetOutConversion))[0], false, "GetOutConversionAccessor"),   // Wrap method
                new(tryGetSpeculativeSemanticModel, false, "TryGetSpeculativeSemanticModelAccessor"),                                       // Wrap method with out parameter
            ]);
        var model = new Dictionary<Type, Strategy>
        {
            { typeof(PrimaryConstructorBaseTypeSyntax), new SyntaxNodeWrapStrategy(typeof(PrimaryConstructorBaseTypeSyntax), typeof(BaseTypeSyntax), null, []) },
            { typeof(SemanticModel), new NoChangeStrategy(typeof(SemanticModel)) },
        };
        var result = sut.Generate(new(model));
        result.Should().BeIgnoringLineEndings(
            """
            //<auto-generated/>
            /*
             * SonarAnalyzer for .NET
             * Copyright (C) SonarSource Sàrl
             * mailto:info AT sonarsource DOT com
             *
             * You can redistribute and/or modify this program under the terms of
             * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
             *
             * This program is distributed in the hope that it will be useful,
             * but WITHOUT ANY WARRANTY; without even the implied warranty of
             * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             * See the Sonar Source-Available License for more details.
             *
             * You should have received a copy of the Sonar Source-Available License
             * along with this program; if not, see https://sonarsource.com/license/ssal/
             */

            using CSharpExtensions = Microsoft.CodeAnalysis.CSharp.CSharpExtensions;
            using Microsoft.CodeAnalysis.CSharp;

            namespace SonarAnalyzer.ShimLayer;

            public static class CSharpExtensionsEx
            {
                private static readonly Type WrappedType = typeof(CSharpExtensions);

                private static readonly Func<ICompoundAssignmentOperation, Conversion> GetOutConversionAccessor = AccessorFactory.CreateStaticMethod<Func<ICompoundAssignmentOperation, Conversion>>(WrappedType, "GetOutConversion");
                private delegate bool TryGetSpeculativeSemanticModelAccessorDelegate(SemanticModel semanticModel, int position, PrimaryConstructorBaseTypeSyntaxWrapper constructorInitializer, out SemanticModel speculativeModel);
                private static readonly TryGetSpeculativeSemanticModelAccessorDelegate TryGetSpeculativeSemanticModelAccessor = AccessorFactory.CreateStaticMethod<TryGetSpeculativeSemanticModelAccessorDelegate>(WrappedType, "TryGetSpeculativeSemanticModel");

                public static Conversion GetOutConversion(this ICompoundAssignmentOperation compoundAssignment) => (Conversion)GetOutConversionAccessor(compoundAssignment);
                public static bool TryGetSpeculativeSemanticModel(this SemanticModel semanticModel, int position, PrimaryConstructorBaseTypeSyntaxWrapper constructorInitializer, out SemanticModel speculativeModel) => (bool)TryGetSpeculativeSemanticModelAccessor(semanticModel, position, constructorInitializer, out speculativeModel);
            }
            """);
    }
}
