/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using System.Text.RegularExpressions;

namespace SonarAnalyzer.ShimLayer.Generator.Strategies;

public abstract class Strategy
{
    // Match 3 or more consecutive newlines (with optional whitespace-only lines between them) and replace with exactly 2 newlines.
    private static readonly Regex ExcessiveNewLines = new(@"\n(\s*\n){2,}", RegexOptions.ExplicitCapture, TimeSpan.FromMilliseconds(100));

    public abstract string ReturnTypeSnippet();
    public abstract string ToConversionSnippet(string from);
    protected abstract string GenerateCore(StrategyModel model);

    public virtual bool IsSupported => true;

    public Type Latest { get; }

    protected Strategy(Type latest) =>
        Latest = latest;

    public virtual string CompiletimeTypeSnippet() =>
        Latest.Name;

    public string Generate(StrategyModel model) =>
        GenerateCore(model) is { } content
            ? ExcessiveNewLines.Replace(content.Replace("\r", null), "\n\n")
            : null;

    public virtual string PropertyAccessorInitializerSnippet(string compiletimeType, string propertyName) =>
        $"""AccessorFactory.CreateProperty<Func<{compiletimeType}, {CompiletimeTypeSnippet()}>>(WrappedType, "{propertyName}")""";

    protected static string JoinLines(IEnumerable<string> lines) =>
       string.Join("\n", lines.Where(x => x is not null));

    protected static string Preamble(params IEnumerable<string> additionalUsing) =>
        $"""
        //<auto-generated/>
        /*
         * SonarAnalyzer for .NET
         * Copyright (C) SonarSource Sàrl
         * mailto:info AT sonarsource DOT com
         *
         * You can redistribute and/or modify this program under the terms of
         * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
         *
         * This program is distributed in the hope that it will be useful,
         * but WITHOUT ANY WARRANTY; without even the implied warranty of
         * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
         * See the Sonar Source-Available License for more details.
         *
         * You should have received a copy of the Sonar Source-Available License
         * along with this program; if not, see https://sonarsource.com/license/ssal/
         */

        {JoinLines((SortedSet<string>)[
            "using Microsoft.CodeAnalysis;",
            "using Microsoft.CodeAnalysis.CSharp;",
            "using Microsoft.CodeAnalysis.CSharp.Syntax;",
            "using Microsoft.CodeAnalysis.Text;",
            "using System;",
            "using System.Collections.Immutable;",
            .. additionalUsing])}

        namespace SonarAnalyzer.ShimLayer;

        """;
}
