language: csharp
os:
  - linux
  - osx

sudo: required
dist: trusty

mono:
  - 4.4.2

dotnet: 2.1.4

script:
  - ./build.sh --verbosity=minimal

notifications:
  email:
    - nancy@nancyfx.org
