/*
 * SonarAnalyzer for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

using System.Diagnostics.CodeAnalysis;
using System.Text;
using Newtonsoft.Json.Linq;

namespace SonarAnalyzer.SourceGenerators;

[Generator]
[ExcludeFromCodeCoverage]
public class SecretExclusionPatternsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Only SonarAnalyzer.Core feeds the shared secret-patterns.json and secret-exclusion-corpus.json as AdditionalFiles (see SonarAnalyzer.Core.csproj),
        // so SecretExclusionPatterns and SecretExclusionCorpus are emitted only there.
        RegisterSource(context, "SecretPatternsFile", "SecretExclusionPatterns.g.cs", GenerateCatalog);
        RegisterSource(context, "SecretExclusionCorpusFile", "SecretExclusionCorpus.g.cs", GenerateCorpus);
    }

    private static void RegisterSource(IncrementalGeneratorInitializationContext context, string metadataName, string hintName, Func<string, string> generate)
    {
        var files = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Where(x => x.Right.GetOptions(x.Left).TryGetValue($"build_metadata.AdditionalFiles.{metadataName}", out var value) && value == "true")
            .Select((x, _) => x.Left)
            .Collect();
        var source = files.Select((x, ct) => CancelableExecute(() => generate(x.IsDefaultOrEmpty ? null : x[0].GetText(ct)?.ToString()), ct));
        context.RegisterSourceOutput(source, (context, source) =>
            {
                if (source is not null)
                {
                    context.AddSource(hintName, source);
                }
            });
    }

    private static T CancelableExecute<T>(Func<T> func, CancellationToken ct) =>
        ct.IsCancellationRequested ? default : func();

    private static string GenerateCatalog(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return null;
        }
        var root = JObject.Parse(json);
        var regexes = root["patternGroups"]?.SelectMany(x => x["patterns"]?.Values<string>() ?? []).Where(x => x is not null).ToArray() ?? [];
        var exactValues = root["exactMatchGroups"]?.SelectMany(x => x["values"]?.Values<string>() ?? []).Where(x => x is not null).ToArray() ?? [];
        var sb = new StringBuilder();
        sb.AppendLine("""
            // <auto-generated/>
            using System.Text.RegularExpressions;

            namespace SonarAnalyzer.Core.Common;

            // Generated by SecretExclusionPatternsGenerator from the shared secret-patterns.json (NET-4087). Do not edit by hand.
            // Regexes are applied case-insensitively with "find" (search-anywhere) semantics; exact values match in full, case-insensitively.
            internal static partial class SecretExclusionPatterns
            {
                public static readonly Regex[] Regexes =
                {
            """);
        foreach (var regex in regexes)
        {
            sb.AppendLine($"        CreateRegex({Encode(regex)}),");
        }
        sb.AppendLine("""
                };

                public static readonly ISet<string> ExactMatches = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
                {
            """);
        foreach (var value in exactValues)
        {
            sb.AppendLine($"        {Encode(value)},");
        }
        sb.AppendLine("""
                };

                private static Regex CreateRegex(string pattern) =>
                    new(pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant, Constants.DefaultRegexTimeout);
            }
            """);
        return sb.ToString();
    }

    // Kept out of SecretExclusionPatterns on purpose: nothing in production reads the corpus, so it must not be allocated by that type's initializer on the first IsKnownNonSecret call.
    private static string GenerateCorpus(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return null;
        }
        var root = JObject.Parse(json);
        var knownNonSecrets = root["knownNonSecrets"]?.Select(x => x["value"]?.Value<string>()).Where(x => x is not null).ToArray() ?? [];
        var secretCandidates = root["secretCandidates"]?.Values<string>().Where(x => x is not null).ToArray() ?? [];
        var sb = new StringBuilder();
        sb.AppendLine("""
            // <auto-generated/>
            namespace SonarAnalyzer.Core.Common;

            // Generated by SecretExclusionPatternsGenerator from the shared secret-exclusion-corpus.json. Do not edit by hand.
            // Test fixture only: the samples SecretExclusionPatterns must classify the way the JVM SecretClassifier does. No production code reads this.
            internal static class SecretExclusionCorpus
            {
                // Every value here must be excluded by SecretExclusionPatterns.
                public static readonly string[] KnownNonSecrets =
                {
            """);
        foreach (var value in knownNonSecrets)
        {
            sb.AppendLine($"        {Encode(value)},");
        }
        sb.AppendLine("""
                };

                // None of these may be excluded: a pattern that is too broad in .NET hides real hardcoded secrets rather than merely adding noise.
                public static readonly string[] SecretCandidates =
                {
            """);
        foreach (var value in secretCandidates)
        {
            sb.AppendLine($"        {Encode(value)},");
        }
        sb.AppendLine("""
                };
            }
            """);
        return sb.ToString();
    }

    private static string Encode(string value) =>
        $@"@""{value.Replace(@"""", @"""""")}""";
}
